# Generated by Django 6.0 on 2025-12-16 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.SlugField(unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_scope',
            field=models.CharField(choices=[('global', 'Вся база'), ('branch', 'Только филиал'), ('self', 'Только мои компании')], default='global', max_length=16, verbose_name='Доступ к базе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('branch_director', 'Директор филиала'), ('group_manager', 'Управляющий группой компаний'), ('admin', 'Администратор')], default='manager', max_length=32, verbose_name='Роль'),
        ),
    ]
