# Generated by Django 6.0 on 2026-01-21 10:52

from django.db import migrations


def _rename_indexes_pg(apps, schema_editor):
    """ALTER INDEX IF EXISTS работает только в PostgreSQL; для SQLite — пропускаем."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "ALTER INDEX IF EXISTS accounts_m_token_h_abc123_idx RENAME TO accounts_ma_token_h_1115dc_idx;"
    )
    schema_editor.execute(
        "ALTER INDEX IF EXISTS accounts_m_user_id_xyz789_idx RENAME TO accounts_ma_user_id_c3f298_idx;"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_merge_0002_0005"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_rename_indexes_pg, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="magiclinktoken",
                    old_name="accounts_m_token_h_abc123_idx",
                    new_name="accounts_ma_token_h_1115dc_idx",
                ),
                migrations.RenameIndex(
                    model_name="magiclinktoken",
                    old_name="accounts_m_user_id_xyz789_idx",
                    new_name="accounts_ma_user_id_c3f298_idx",
                ),
            ],
        ),
    ]
