# Generated by Django 6.0 on 2026-01-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_0002_0005'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='magiclinktoken',
            new_name='accounts_ma_token_h_1115dc_idx',
            old_name='accounts_m_token_h_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='magiclinktoken',
            new_name='accounts_ma_user_id_c3f298_idx',
            old_name='accounts_m_user_id_xyz789_idx',
        ),
    ]
