# Generated by Django 6.0 on 2026-04-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_branch_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messenger_last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность в мессенджере'),
        ),
        migrations.AddField(
            model_name='user',
            name='messenger_online',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Онлайн в мессенджере'),
        ),
    ]
