# Generated by Django 6.0 on 2026-04-13 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_messenger_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(db_index=True, max_length=128, verbose_name='Регион')),
                ('is_common_pool', models.BooleanField(default=False, help_text='Москва/МО, СПб/ЛО, Новгородская, Псковская — обслуживаются равномерно всеми филиалами', verbose_name='Общий пул')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='accounts.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Регион филиала',
                'verbose_name_plural': 'Регионы филиалов',
                'ordering': ['branch', 'ordering'],
                'indexes': [models.Index(fields=['region_name', 'branch'], name='accounts_br_region__1077a4_idx'), models.Index(fields=['is_common_pool'], name='accounts_br_is_comm_149a99_idx')],
                'unique_together': {('branch', 'region_name')},
            },
        ),
    ]
