# Generated by Django 6.0 on 2026-04-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_branch_regions_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('branch_director', 'Директор подразделения'), ('sales_head', 'РОП'), ('group_manager', 'Управляющий группой компаний'), ('tenderist', 'Тендерист'), ('admin', 'Администратор')], default='manager', max_length=32, verbose_name='Роль'),
        ),
    ]
