# Generated by Django 6.0 on 2026-04-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_tenderist_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchregion',
            options={'ordering': ['branch', 'ordering'], 'verbose_name': 'Регион подразделения', 'verbose_name_plural': 'Регионы подразделений'},
        ),
        migrations.RemoveIndex(
            model_name='magiclinktoken',
            name='accounts_ma_token_h_1115dc_idx',
        ),
        migrations.AlterField(
            model_name='branchregion',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='accounts.branch', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='branchregion',
            name='is_common_pool',
            field=models.BooleanField(default=False, help_text='Москва/МО, СПб/ЛО, Новгородская, Псковская — обслуживаются равномерно всеми подразделениями', verbose_name='Общий пул'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.branch', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_scope',
            field=models.CharField(choices=[('global', 'Вся база'), ('branch', 'Только подразделение'), ('self', 'Только мои компании')], default='global', max_length=16, verbose_name='Доступ к базе'),
        ),
    ]
