# Generated by Django 6.0.4 on 2026-04-22 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userabsence_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text='Generated on setup, shared with authenticator app via QR.', max_length=32, verbose_name='TOTP secret (base32)')),
                ('confirmed', models.BooleanField(default=False, help_text='True после successful verify 6-digit кода на setup.', verbose_name='Confirmed (активное устройство)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_totp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TOTP устройство (admin)',
                'verbose_name_plural': 'TOTP устройства (admin)',
            },
        ),
        migrations.CreateModel(
            name='AdminRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, verbose_name='SHA-256 hash')),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recovery code (admin)',
                'verbose_name_plural': 'Recovery codes (admin)',
                'indexes': [models.Index(fields=['user', 'used'], name='accounts_ad_user_id_ea5c92_idx')],
            },
        ),
    ]
