# Generated by Django 6.0 on 2026-01-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mode", models.CharField(choices=[("observe_only", "Наблюдение (не блокировать, только логировать)"), ("enforce", "Применять (блокировать запрещённые действия)")], db_index=True, default="observe_only", max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("priority", models.IntegerField(db_index=True, default=100, help_text="Меньше = выше приоритет")),
                ("subject_type", models.CharField(choices=[("role", "Роль"), ("user", "Пользователь")], db_index=True, max_length=16)),
                ("role", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                ("resource_type", models.CharField(choices=[("page", "Страница"), ("action", "Действие")], db_index=True, max_length=16)),
                ("resource", models.CharField(db_index=True, max_length=120)),
                ("effect", models.CharField(choices=[("allow", "Разрешить"), ("deny", "Запретить")], db_index=True, max_length=8)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="policy_rules", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["enabled", "resource_type", "resource"], name="policy_polic_enabl_1dcd8a_idx"),
                    models.Index(fields=["subject_type", "role"], name="policy_polic_subjec_d4c97a_idx"),
                    models.Index(fields=["subject_type", "user"], name="policy_polic_subjec_9d8a19_idx"),
                    models.Index(fields=["priority"], name="policy_polic_priorit_563d7c_idx"),
                ],
            },
        ),
    ]

