# Generated by Django 6.0 on 2026-01-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="policyrule",
            old_name="policy_polic_enabl_1dcd8a_idx",
            new_name="policy_poli_enabled_f6960e_idx",
        ),
        migrations.RenameIndex(
            model_name="policyrule",
            old_name="policy_polic_subjec_d4c97a_idx",
            new_name="policy_poli_subject_939a08_idx",
        ),
        migrations.RenameIndex(
            model_name="policyrule",
            old_name="policy_polic_subjec_9d8a19_idx",
            new_name="policy_poli_subject_91565a_idx",
        ),
        migrations.RenameIndex(
            model_name="policyrule",
            old_name="policy_polic_priorit_563d7c_idx",
            new_name="policy_poli_priorit_7ffb89_idx",
        ),
    ]

