# Generated by Django 6.0.1 on 2026-02-16 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_rename_accounts_m_token_h_abc123_idx_accounts_ma_token_h_1115dc_idx_and_more'),
        ('companies', '0048_note_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL аватара')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Отображаемое имя')),
                ('status', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн')], db_index=True, default='offline', max_length=16, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль оператора',
                'verbose_name_plural': 'Профили операторов',
            },
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('body', models.TextField(verbose_name='Текст ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to='accounts.branch', verbose_name='Филиал')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_canned_responses', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Шаблон ответа',
                'verbose_name_plural': 'Шаблоны ответов',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, default='', help_text='Идентификатор во внешней системе (visitor_id, Telegram user_id и т.п.)', max_length=255, verbose_name='Внешний ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('region_detected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_contacts', to='companies.region', verbose_name='Определённый регион')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('widget_token', models.CharField(help_text='Секретный токен для подключения виджета с сайта.', max_length=64, unique=True, verbose_name='Токен виджета')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inboxes', to='accounts.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Inbox',
                'verbose_name_plural': 'Inboxes',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('pending', 'В ожидании'), ('resolved', 'Решён'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=16, verbose_name='Статус')),
                ('priority', models.IntegerField(choices=[(10, 'Низкий'), (20, 'Обычный'), (30, 'Высокий')], db_index=True, default=20, verbose_name='Приоритет')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время последнего сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный оператор')),
                ('branch', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='messenger_conversations', to='accounts.branch', verbose_name='Филиал')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='messenger.contact', verbose_name='Контакт')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_conversations', to='companies.region', verbose_name='Регион')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='messenger.inbox', verbose_name='Inbox')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('website', 'Сайт'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('vk', 'VK'), ('email', 'Email')], max_length=32, verbose_name='Тип')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='messenger.inbox', verbose_name='Inbox')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'Входящее'), ('out', 'Исходящее'), ('internal', 'Внутренняя заметка')], db_index=True, max_length=16, verbose_name='Направление')),
                ('body', models.TextField(blank=True, default='', verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.conversation', verbose_name='Диалог')),
                ('sender_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='messenger.contact', verbose_name='Контакт-отправитель')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='messenger/attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла')),
                ('content_type', models.CharField(blank=True, default='', max_length=120, verbose_name='MIME тип')),
                ('size', models.BigIntegerField(default=0, verbose_name='Размер (байт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Загружено')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messenger.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение сообщения',
                'verbose_name_plural': 'Вложения сообщений',
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('priority', models.IntegerField(db_index=True, default=100, verbose_name='Приоритет')),
                ('is_fallback', models.BooleanField(default=False, help_text='Используется, если не найдено ни одного подходящего правила по региону.', verbose_name='Фолбэк-правило')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_routing_rules', to='accounts.branch', verbose_name='Филиал')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='messenger.inbox', verbose_name='Inbox')),
                ('regions', models.ManyToManyField(blank=True, related_name='messenger_routing_rules', to='companies.region', verbose_name='Регионы')),
            ],
            options={
                'verbose_name': 'Правило маршрутизации',
                'verbose_name_plural': 'Правила маршрутизации',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['external_id'], name='messenger_c_externa_e3d5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='messenger_c_email_ffa4e2_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='messenger_c_phone_525868_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['branch', 'status'], name='messenger_c_branch__68dc84_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='messenger_c_created_d1682a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='messenger_c_last_me_a91c41_idx'),
        ),
    ]
