# Generated by Django 6.0.1 on 2026-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='widget_token',
            field=models.CharField(help_text='Секретный токен для подключения виджета с сайта. Генерируется автоматически при создании, если не указан.', max_length=64, unique=True, verbose_name='Токен виджета'),
        ),
    ]
