# Generated by Django 6.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_inbox_widget_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='branch',
            field=models.ForeignKey(
                blank=True,
                help_text='Пусто = общий (глобальный) inbox: филиал диалога определяется по GeoIP и правилам маршрутизации.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='inboxes',
                to='accounts.branch',
                verbose_name='Филиал',
            ),
        ),
    ]
