# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0003_inbox_branch_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="assignee_assigned_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Время последнего назначения; используется для эскалации по таймауту.",
                null=True,
                verbose_name="Когда назначен оператор",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="assignee_opened_at",
            field=models.DateTimeField(
                blank=True,
                help_text="После открытия эскалация по таймауту не выполняется.",
                null=True,
                verbose_name="Когда оператор впервые открыл диалог",
            ),
        ),
    ]
