# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0004_conversation_assignee_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="assignee_last_read_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Для подсчёта непрочитанных входящих сообщений.",
                null=True,
                verbose_name="Когда оператор последний раз просматривал диалог",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Для исходящих: когда контакт увидел сообщение (виджет).",
                null=True,
                verbose_name="Прочитано (контакт)",
            ),
        ),
    ]
