# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0005_conversation_assignee_last_read_message_read_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="rating_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                help_text="Оценка от контакта после закрытия диалога.",
                null=True,
                verbose_name="Оценка (1–5 или 0–10 NPS)",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="rating_comment",
            field=models.TextField(blank=True, default="", verbose_name="Комментарий к оценке"),
        ),
        migrations.AddField(
            model_name="conversation",
            name="rated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Когда оценено"),
        ),
    ]
