# Generated by Django 6.0.1 on 2026-02-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_conversation_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='status',
            field=models.CharField(choices=[('online', 'Онлайн'), ('away', 'Отошёл'), ('busy', 'Занят'), ('offline', 'Офлайн')], db_index=True, default='offline', max_length=16, verbose_name='Статус'),
        ),
    ]
