# Generated by Django 6.0.1 on 2026-02-20 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_accounts_m_token_h_abc123_idx_accounts_ma_token_h_1115dc_idx_and_more'),
        ('companies', '0048_note_attachments'),
        ('messenger', '0007_alter_agentprofile_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.TextField(help_text='Идентификатор контакта в inbox (например, visitor_id для виджета).', verbose_name='ID источника')),
                ('pubsub_token', models.CharField(blank=True, help_text='Токен для WebSocket подключения (генерируется автоматически).', max_length=64, unique=True, verbose_name='PubSub токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Связь контакта с inbox',
                'verbose_name_plural': 'Связи контактов с inbox',
            },
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='messenger_c_last_me_a91c41_idx',
        ),
        # Переименовать last_message_at в last_activity_at для Conversation
        migrations.RenameField(
            model_name='conversation',
            old_name='last_message_at',
            new_name='last_activity_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='blocked',
            field=models.BooleanField(db_index=True, default=False, help_text='Заблокированный контакт. Используется для mute диалогов.', verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Обновляется при создании входящего сообщения.', null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='message',
            name='content_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Структурированные данные: in_reply_to, deleted, translations и т.д.', verbose_name='Атрибуты контента'),
        ),
        migrations.AddField(
            model_name='message',
            name='external_source_ids',
            field=models.JSONField(blank=True, default=dict, help_text='ID во внешних системах (Slack, Telegram и т.д.).', verbose_name='ID внешних источников'),
        ),
        migrations.AddField(
            model_name='message',
            name='processed_message_content',
            field=models.TextField(blank=True, default='', help_text='Обработанный контент (после фильтрации, форматирования). Максимум 150,000 символов.', verbose_name='Обработанный контент'),
        ),
        migrations.AddField(
            model_name='message',
            name='source_id',
            field=models.TextField(blank=True, db_index=True, help_text='ID источника для дедупликации.', null=True, verbose_name='ID источника'),
        ),
        # Добавить новые поля в Conversation
        migrations.AddField(
            model_name='conversation',
            name='additional_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Метаданные: referer, browser, OS, IP и т.д.', verbose_name='Дополнительные атрибуты'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='agent_last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда агент последний раз видел диалог'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact_last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда контакт последний раз видел диалог'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Кастомные атрибуты для гибкости.', verbose_name='Кастомные атрибуты'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='first_reply_created_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Используется для метрик времени первого ответа.', null=True, verbose_name='Время первого ответа оператора'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='identifier',
            field=models.CharField(blank=True, help_text='Идентификатор из внешней системы.', max_length=255, null=True, verbose_name='Идентификатор'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отложен до'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='waiting_since',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Устанавливается при создании диалога или входящем сообщении. Очищается при первом ответе.', null=True, verbose_name='Когда начал ждать ответа'),
        ),
        # Обновить help_text для last_activity_at (уже переименовано выше)
        migrations.AlterField(
            model_name='conversation',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Обновляется при каждом сообщении. Fallback на created_at.', null=True, verbose_name='Время последней активности'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Максимум 150,000 символов (как в Chatwoot).', verbose_name='Текст сообщения'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_activity_at'], name='messenger_c_last_ac_7ce3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['blocked'], name='messenger_c_blocked_68c537_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_activity_at'], name='messenger_c_last_ac_3030f9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['waiting_since'], name='messenger_c_waiting_441505_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['first_reply_created_at'], name='messenger_c_first_r_5ba7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'direction', 'created_at'], name='messenger_m_convers_6691f2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['source_id'], name='messenger_m_source__d2b990_idx'),
        ),
        migrations.AddField(
            model_name='contactinbox',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_inboxes', to='messenger.contact', verbose_name='Контакт'),
        ),
        migrations.AddField(
            model_name='contactinbox',
            name='inbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_inboxes', to='messenger.inbox', verbose_name='Inbox'),
        ),
        migrations.AddIndex(
            model_name='contactinbox',
            index=models.Index(fields=['inbox', 'source_id'], name='messenger_c_inbox_i_327d02_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinbox',
            index=models.Index(fields=['pubsub_token'], name='messenger_c_pubsub__bc65ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactinbox',
            unique_together={('inbox', 'source_id')},
        ),
    ]
