# Generated by Django 6.0 on 2026-04-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_add_composite_indexes_phase2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Метка диалога',
                'verbose_name_plural': 'Метки диалогов',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='messenger.conversationlabel', verbose_name='Метки'),
        ),
    ]
