# Generated by Django 6.0 on 2026-04-03 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0013_add_push_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('event_name', models.CharField(choices=[('conversation_created', 'Диалог создан'), ('message_created', 'Сообщение создано'), ('conversation_updated', 'Диалог обновлён')], max_length=32, verbose_name='Событие')),
                ('conditions', models.JSONField(default=list, help_text='[{"attribute_key": "status", "filter_operator": "equal_to", "values": ["open"]}]', verbose_name='Условия')),
                ('actions', models.JSONField(default=list, help_text='[{"action_name": "assign_agent", "action_params": [42]}]', verbose_name='Действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbox', models.ForeignKey(blank=True, help_text='Если пусто — правило для всех инбоксов', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='messenger.inbox')),
            ],
            options={
                'verbose_name': 'Правило автоматизации',
                'verbose_name_plural': 'Правила автоматизации',
                'indexes': [models.Index(fields=['event_name', 'is_active'], name='messenger_a_event_n_fb30e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('url_pattern', models.CharField(blank=True, default='*', help_text='Wildcard-паттерн URL страницы (например, */pricing*)', max_length=500, verbose_name='URL-паттерн')),
                ('time_on_page', models.PositiveIntegerField(default=10, help_text='Через сколько секунд показать сообщение', verbose_name='Секунд на странице')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('disabled', 'Отключена')], default='active', max_length=16, verbose_name='Статус')),
                ('only_during_business_hours', models.BooleanField(default=False, verbose_name='Только в рабочее время')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='messenger.inbox')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
                'indexes': [models.Index(fields=['inbox', 'status'], name='messenger_c_inbox_i_2f8b87_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('first_response', 'Первый ответ'), ('reply_time', 'Время ответа'), ('conversation_resolved', 'Решён'), ('conversation_opened', 'Открыт')], max_length=32, verbose_name='Тип')),
                ('value', models.FloatField(default=0, verbose_name='Значение (секунды)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_events', to='messenger.conversation')),
                ('inbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messenger.inbox')),
                ('user', models.ForeignKey(blank=True, help_text='Оператор (для метрик по агентам)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие аналитики',
                'verbose_name_plural': 'События аналитики',
                'indexes': [models.Index(fields=['name', 'created_at'], name='messenger_r_name_39da84_idx'), models.Index(fields=['name', 'inbox', 'created_at'], name='messenger_r_name_96c4a6_idx'), models.Index(fields=['name', 'user', 'created_at'], name='messenger_r_name_cb6a5a_idx')],
            },
        ),
    ]
