# Generated by Django 6.0 on 2026-04-03 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0014_add_campaigns_automations_reporting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('actions', models.JSONField(default=list, help_text='[{"action_name": "assign_agent", "action_params": [42]}, {"action_name": "send_message", "action_params": ["Спасибо!"]}]', verbose_name='Действия')),
                ('visibility', models.CharField(choices=[('personal', 'Личный'), ('global', 'Общий')], default='personal', max_length=16, verbose_name='Видимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Владелец макроса (null = общий)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messenger_macros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Макрос',
                'verbose_name_plural': 'Макросы',
                'indexes': [models.Index(fields=['user', 'visibility'], name='messenger_m_user_id_789637_idx')],
            },
        ),
    ]
