# Generated by Django 6.0 on 2026-04-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_add_macro'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='client_region',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Определён по GeoIP / pre-chat анкете / компании клиента', max_length=128, verbose_name='Регион клиента'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='client_region_source',
            field=models.CharField(blank=True, choices=[('geoip', 'GeoIP'), ('form', 'Анкета'), ('company', 'Компания'), ('', 'Не определён')], default='', max_length=16, verbose_name='Источник региона'),
        ),
    ]
