# Generated by Django 6.0 on 2026-04-13 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_branch_regions_data'),
        ('messenger', '0016_conversation_client_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина передачи')),
                ('cross_branch', models.BooleanField(default=False, verbose_name='Межфилиальная передача')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='messenger.conversation', verbose_name='Диалог')),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_transfers_out', to='accounts.branch', verbose_name='Филиал-источник')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_transfers_from', to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messenger_transfers_in', to='accounts.branch', verbose_name='Филиал-получатель')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messenger_transfers_to', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Передача диалога',
                'verbose_name_plural': 'Передачи диалогов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', '-created_at'], name='messenger_c_convers_1f0474_idx'), models.Index(fields=['to_user', '-created_at'], name='messenger_c_to_user_5bc9b1_idx')],
            },
        ),
    ]
