# Generated by Django 6.0 on 2026-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0018_message_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='needs_help',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Требует помощи'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='needs_help_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время запроса помощи'),
        ),
    ]
