# Generated by Django 6.0 on 2026-04-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0019_conversation_needs_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_agent_msg_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последнее сообщение оператора'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_customer_msg_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последнее сообщение клиента'),
        ),
    ]
