# Generated by Django 6.0 on 2026-04-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0020_conversation_msg_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cannedresponse',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'Шаблон ответа', 'verbose_name_plural': 'Шаблоны ответов'},
        ),
        migrations.AddField(
            model_name='cannedresponse',
            name='is_quick_button',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Показывать как быструю кнопку'),
        ),
        migrations.AddField(
            model_name='cannedresponse',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
