# Generated by Django 6.0 on 2026-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0021_cannedresponse_quick_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='0=нет, 1=warn, 2=urgent, 3=rop_alert, 4=pool_return', verbose_name='Уровень эскалации'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней эскалации'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='resolution',
            field=models.JSONField(blank=True, default=dict, help_text='Структура {outcome, comment, resolved_at} из resolve modal', verbose_name='Итог резолюции'),
        ),
    ]
