# Generated by Django 6.0 on 2026-04-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0051_companynote_sms_type'),
        ('messenger', '0022_conversation_escalation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Автосвязь по email/phone контакта. Может быть переназначена вручную.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_conversations', to='companies.company', verbose_name='Компания клиента'),
        ),
    ]
