# Generated by Django 6.0 on 2026-04-16 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_duplicate_magiclink_index'),
        ('companies', '0052_task_indexes_and_constraints'),
        ('messenger', '0023_conversation_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cannedresponse',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to='accounts.branch', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='branch',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='messenger_conversations', to='accounts.branch', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='conversationtransfer',
            name='cross_branch',
            field=models.BooleanField(default=False, verbose_name='Передача между подразделениями'),
        ),
        migrations.AlterField(
            model_name='conversationtransfer',
            name='from_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_transfers_out', to='accounts.branch', verbose_name='Подразделение-источник'),
        ),
        migrations.AlterField(
            model_name='conversationtransfer',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messenger_transfers_in', to='accounts.branch', verbose_name='Подразделение-получатель'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Пусто = общий (глобальный) inbox: подразделение диалога определяется по GeoIP и правилам маршрутизации.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inboxes', to='accounts.branch', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_routing_rules', to='accounts.branch', verbose_name='Подразделение'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'pending', 'resolved', 'closed'])), name='conversation_valid_status'),
        ),
    ]
