# Generated by Django 6.0.4 on 2026-04-20 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userabsence_id'),
        ('companies', '0054_contract_type_amount_thresholds'),
        ('messenger', '0025_conversation_off_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='conversation_valid_status',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('pending', 'В ожидании'), ('waiting_offline', 'Ждёт связи (вне часов)'), ('resolved', 'Решён'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=16, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'pending', 'resolved', 'closed'])), name='conversation_valid_status'),
        ),
    ]
