# Generated by Django 6.0.4 on 2026-04-20 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userabsence_id'),
        ('companies', '0054_contract_type_amount_thresholds'),
        ('messenger', '0026_remove_conversation_conversation_valid_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='conversation_valid_status',
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'pending', 'waiting_offline', 'resolved', 'closed'])), name='conversation_valid_status'),
        ),
    ]
