"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

from celery.schedules import crontab
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Директория для логов (в Docker при монтировании backend/ может быть недоступна для записи — тогда только console)
LOGS_DIR = BASE_DIR / "logs"
try:
    LOGS_DIR.mkdir(exist_ok=True)
except OSError:
    pass
_use_file_logging = LOGS_DIR.exists() and os.access(str(LOGS_DIR), os.W_OK)

# Загружаем .env из корня проекта (для Docker) или из backend/.env (для локальной разработки)
# Сначала пробуем корень проекта (на уровень выше backend/)
PROJECT_ROOT = BASE_DIR.parent
env_path = PROJECT_ROOT / ".env"
if not env_path.exists():
    # Если нет в корне, пробуем в backend/
    env_path = BASE_DIR / ".env"
try:
    load_dotenv(env_path)
except Exception:
    # Если не удалось загрузить, пробуем стандартный путь
    load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"

# Проверка: в production DEBUG должен быть выключен
# Если DJANGO_DEBUG не установлен явно, считаем это ошибкой конфигурации в production
# (определяем production по наличию не-dev значений в ALLOWED_HOSTS или явному DJANGO_DEBUG=0)
_django_debug_env = os.getenv("DJANGO_DEBUG", "").strip()
_is_production_like = any(
    h not in ("localhost", "127.0.0.1") 
    for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") 
    if h.strip()
)
if _is_production_like and _django_debug_env != "0" and DEBUG:
    import warnings
    warnings.warn(
        "⚠️ SECURITY WARNING: DEBUG=True detected in production-like environment. "
        "Set DJANGO_DEBUG=0 explicitly. Continuing with DEBUG=True (unsafe).",
        UserWarning,
        stacklevel=2,
    )

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]
# For Cloudflare Tunnel / proxies: add full origins with scheme, e.g. "https://*.trycloudflare.com"
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]

# Trust proxy headers (X-Forwarded-For, X-Forwarded-Host) only from our own proxy
# В production: установить IP прокси через DJANGO_PROXY_IPS (через запятую)
# Например: DJANGO_PROXY_IPS="127.0.0.1,10.0.0.1" для Nginx/балансера
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_FOR = True
PROXY_IPS = [ip.strip() for ip in os.getenv("DJANGO_PROXY_IPS", "").split(",") if ip.strip()]

# Production hardening (when DEBUG=0)
if not DEBUG:
    if SECRET_KEY in ("dev-secret-key-change-me", "", None) or str(SECRET_KEY).startswith("django-insecure-") or len(str(SECRET_KEY)) < 50:
        raise ImproperlyConfigured("Set a strong DJANGO_SECRET_KEY (50+ chars) for production.")

    # F11 (2026-04-18): запрет на wildcard в ALLOWED_HOSTS в проде —
    # это классический вектор host-header атак. localhost/127.0.0.1
    # оставляем разрешёнными: nginx/docker используют их для internal
    # health-check, это не ведёт к утечке (nginx фильтрует Host снаружи).
    if "*" in ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "DJANGO_ALLOWED_HOSTS содержит '*'. В проде это запрещено — "
            "укажите явный список доменов через запятую."
        )

    # F11: CSRF_TRUSTED_ORIGINS должен быть задан, иначе POST с cookie-auth
    # будет падать с 403 на любых доменах кроме same-origin.
    if not CSRF_TRUSTED_ORIGINS:
        import warnings
        warnings.warn(
            "⚠️ DJANGO_CSRF_TRUSTED_ORIGINS не задан. В проде крайне рекомендуется — "
            "укажите https://crm.groupprofi.ru (и staging domain, если нужно). "
            "Иначе POST-запросы с cookie-auth могут падать 403.",
            UserWarning,
            stacklevel=2,
        )

    # When running behind a reverse proxy (Nginx) that sets X-Forwarded-Proto.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "1") == "1"
    SECURE_REDIRECT_EXEMPT = [r"^health/$"]
    SESSION_COOKIE_SECURE = os.getenv("DJANGO_SESSION_COOKIE_SECURE", "1") == "1"
    CSRF_COOKIE_SECURE = os.getenv("DJANGO_CSRF_COOKIE_SECURE", "1") == "1"

    # HSTS: безопасный дефолт 1 час. Можно поставить 0 через env, если домен не всегда под HTTPS.
    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "3600") or "3600")
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "0") == "1"
    SECURE_HSTS_PRELOAD = os.getenv("DJANGO_SECURE_HSTS_PRELOAD", "0") == "1"
    
    # Дополнительные security headers для защиты от утечки информации
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
    
    # Защита от утечки информации через ошибки
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    
    # Content Security Policy (CSP) - защита от XSS
    # Разрешаем только доверенные источники для скриптов и стилей
    CSP_DEFAULT_SRC = os.getenv("CSP_DEFAULT_SRC", "'self'")
    CSP_SCRIPT_SRC = os.getenv("CSP_SCRIPT_SRC", "'self' 'unsafe-inline'")
    CSP_STYLE_SRC = os.getenv("CSP_STYLE_SRC", "'self' 'unsafe-inline'")
    CSP_IMG_SRC = os.getenv("CSP_IMG_SRC", "'self' data: https: blob:")
    CSP_FONT_SRC = os.getenv("CSP_FONT_SRC", "'self' data:")
    CSP_CONNECT_SRC = os.getenv("CSP_CONNECT_SRC", "'self'")
    
    # Формируем CSP заголовок (только в production)
    CSP_HEADER = (
        f"default-src {CSP_DEFAULT_SRC}; "
        f"script-src {CSP_SCRIPT_SRC}; "
        f"style-src {CSP_STYLE_SRC}; "
        f"img-src {CSP_IMG_SRC}; "
        f"font-src {CSP_FONT_SRC}; "
        f"connect-src {CSP_CONNECT_SRC}; "
        "frame-ancestors 'none'; "
        "base-uri 'self'; "
        "form-action 'self';"
    )
else:
    # В development режиме CSP не применяется (может мешать разработке)
    CSP_HEADER = None

# Magic Link Authentication
# Если установлено в 1, вход по паролю отключается (только magic links)
MAGIC_LINK_ONLY = os.getenv("MAGIC_LINK_ONLY", "0") == "1"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',  # Для PostgreSQL-специфичных функций (pg_trgm, full-text search)

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    # Включаем blacklist для возможности отзыва refresh-токенов
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
    'drf_spectacular',  # OpenAPI 3.0 schema generation
    'channels',  # Django Channels for WebSocket support

    # Local apps
    'accounts',
    'companies',
    'tasksapp',
    'ui',
    'audit',
    'mailer',
    'notifications',
    'phonebridge',
    'amocrm',  # AmoCRM integration (migration tools and management commands)
    'policy',
    'messenger',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'core.request_id.RequestIdMiddleware',  # Добавляет request_id для корреляции логов
    'django.middleware.security.SecurityMiddleware',
    # Serve static files in production (admin CSS/JS) without relying on DEBUG=1.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'accounts.middleware.RateLimitMiddleware',  # Защита от DDoS и rate limiting
    'crm.middleware.SecurityHeadersMiddleware',  # Дополнительные security headers (CSP, Permissions-Policy)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crm.middleware.ErrorLoggingMiddleware',  # Логирование ошибок в БД
]

ROOT_URLCONF = 'crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ui.context_processors.ui_globals',
                'notifications.context_processors.notifications_panel',
                'crm.context_processors.csp_nonce',
            ],
        },
    },
]

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

WSGI_APPLICATION = 'crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.getenv("DB_ENGINE", "sqlite")
if DB_ENGINE == "postgres":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "crm"),
            "USER": os.getenv("POSTGRES_USER", "crm"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "crm"),
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": int(os.getenv("POSTGRES_PORT", "5432")),
            "OPTIONS": {
                "connect_timeout": 10,  # Таймаут подключения 10 секунд
                "options": "-c statement_timeout=300000",  # 5 минут на запрос (для импорта)
            },
            "CONN_MAX_AGE": 600,  # Переиспользование соединений до 10 минут
        }
    }
else:
    if _is_production_like:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            "DB_ENGINE is not set to 'postgres' in a production-like environment. "
            "Set DB_ENGINE=postgres in your .env file."
        )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = os.getenv("DJANGO_LANGUAGE_CODE", "ru-ru")

TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "Europe/Moscow")

USE_I18N = True

USE_TZ = True

# Настройки сессий для безопасности
# Длительность сессии в секундах. По умолчанию 2 недели (1209600), чтобы сотрудникам не нужно
# было каждую неделю получать новую ссылку входа. Можно задать через DJANGO_SESSION_COOKIE_AGE в .env.
SESSION_COOKIE_AGE = int(os.getenv("DJANGO_SESSION_COOKIE_AGE", "1209600"))  # 2 недели (14 * 24 * 3600)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"  # Защита от CSRF
# При каждом запросе продлевать сессию (скользящее окно): пока сотрудник пользуется сайтом —
# сессия не истекает; если не заходил 2 недели — выйдет. Удобно и безопасно.
SESSION_SAVE_EVERY_REQUEST = True

# Mailer encryption key (Fernet). Generate once and store in env on VDS.
MAILER_FERNET_KEY = os.getenv("MAILER_FERNET_KEY", "")
# Старые ключи Fernet для расшифровки уже зашифрованных значений после
# ротации. Формат: запятой-разделённый список base64 URL-safe ключей.
MAILER_FERNET_KEYS_OLD = [
    k.strip() for k in os.getenv("MAILER_FERNET_KEYS_OLD", "").split(",") if k.strip()
]

# В production MAILER_FERNET_KEY обязателен — без него пароли SMTP хранятся в plaintext.
# Генерация: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
if not DEBUG and not MAILER_FERNET_KEY:
    raise ImproperlyConfigured(
        "MAILER_FERNET_KEY is not set. Email account passwords cannot be encrypted. "
        "Generate: python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
    )

# Public base URL for emails/unsubscribe (optional; example: https://crm.example.ru)
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "")

# Mailer: размер батча отправки (получателей за один проход задачи)
MAILER_SEND_BATCH_SIZE = int(os.getenv("MAILER_SEND_BATCH_SIZE", "10"))
# Mailer: таймаут Redis-лока задачи send_pending_emails (секунды)
MAILER_SEND_LOCK_TIMEOUT = int(os.getenv("MAILER_SEND_LOCK_TIMEOUT", "120"))
# Mailer: максимум получателей в кампании
MAILER_MAX_CAMPAIGN_RECIPIENTS = int(os.getenv("MAILER_MAX_CAMPAIGN_RECIPIENTS", "10000"))

# Security contact email for security.txt
SECURITY_CONTACT_EMAIL = os.getenv("SECURITY_CONTACT_EMAIL", "")

AUTH_USER_MODEL = "accounts.User"

# Messenger feature flag и настройки live-chat / widget
MESSENGER_ENABLED = os.getenv("MESSENGER_ENABLED", "0") == "1"
# Филиал по умолчанию для глобального inbox, когда ни одно правило маршрутизации не сработало (ID филиала).
MESSENGER_DEFAULT_BRANCH_ID = os.getenv("MESSENGER_DEFAULT_BRANCH_ID", "")
if MESSENGER_DEFAULT_BRANCH_ID:
    try:
        MESSENGER_DEFAULT_BRANCH_ID = int(MESSENGER_DEFAULT_BRANCH_ID)
    except (ValueError, TypeError):
        MESSENGER_DEFAULT_BRANCH_ID = None
else:
    MESSENGER_DEFAULT_BRANCH_ID = None
# Включить определение региона по IP (GeoIP) при bootstrap виджета. 0 = выключено.
MESSENGER_GEOIP_ENABLED = os.getenv("MESSENGER_GEOIP_ENABLED", "1") == "1"
# Сообщение в ответе bootstrap виджета, когда запрос вне рабочих часов (виджет может показать его посетителю).
MESSENGER_OUTSIDE_WORKING_HOURS_MESSAGE = os.getenv(
    "MESSENGER_OUTSIDE_WORKING_HOURS_MESSAGE",
    "Мы ответим в рабочее время.",
)
# Таймаут эскалации (секунды): если оператор не открыл диалог за это время — переназначение следующему. По умолчанию 4 мин.
MESSENGER_ESCALATION_TIMEOUT_SECONDS = int(os.getenv("MESSENGER_ESCALATION_TIMEOUT_SECONDS", "240"))
MESSENGER_AUTO_RESOLVE_HOURS = int(os.getenv("MESSENGER_AUTO_RESOLVE_HOURS", "24"))

# Политика хранения: через сколько дней переводить RESOLVED → CLOSED (архивировать). По умолчанию 90 дней.
MESSENGER_RETENTION_RESOLVED_TO_CLOSED_DAYS = int(os.getenv("MESSENGER_RETENTION_RESOLVED_TO_CLOSED_DAYS", "90"))

# Throttling / abuse‑защита публичного Widget API (переопределяются через env на проде)
MESSENGER_WIDGET_BOOTSTRAP_RATE_PER_IP = int(os.getenv("MESSENGER_WIDGET_BOOTSTRAP_RATE_PER_IP", "10"))
MESSENGER_WIDGET_BOOTSTRAP_RATE_PER_TOKEN = int(os.getenv("MESSENGER_WIDGET_BOOTSTRAP_RATE_PER_TOKEN", "20"))
MESSENGER_WIDGET_SEND_RATE_PER_SESSION = int(os.getenv("MESSENGER_WIDGET_SEND_RATE_PER_SESSION", "30"))
MESSENGER_WIDGET_SEND_RATE_PER_IP = int(os.getenv("MESSENGER_WIDGET_SEND_RATE_PER_IP", "60"))
MESSENGER_WIDGET_POLL_RATE_PER_SESSION = int(os.getenv("MESSENGER_WIDGET_POLL_RATE_PER_SESSION", "60"))
MESSENGER_WIDGET_POLL_MIN_INTERVAL_SECONDS = int(
    os.getenv("MESSENGER_WIDGET_POLL_MIN_INTERVAL_SECONDS", "2")
)

# Secure-by-default allowlist доменов для виджета.
# Если True (прод-дефолт), при пустом allowlist запрос блокируется.
# Если False (dev), пустой allowlist пропускает запрос (обратная совместимость).
MESSENGER_WIDGET_STRICT_ORIGIN = os.getenv(
    "MESSENGER_WIDGET_STRICT_ORIGIN",
    "0" if DEBUG else "1",
) == "1"
# Глобальный allowlist доменов (через запятую) — добавляется к inbox.allowed_domains.
MESSENGER_WIDGET_GLOBAL_ALLOWED_DOMAINS = [
    d.strip() for d in os.getenv("MESSENGER_WIDGET_GLOBAL_ALLOWED_DOMAINS", "").split(",") if d.strip()
]

# Privacy‑настройки для публичного виджета (минимальное уведомление о данных)
MESSENGER_PRIVACY_URL = os.getenv("MESSENGER_PRIVACY_URL", "")
MESSENGER_PRIVACY_TEXT = os.getenv(
    "MESSENGER_PRIVACY_TEXT",
    "Отправляя сообщение, вы соглашаетесь с обработкой персональных данных.",
)

# Web Push (VAPID) — для browser push-уведомлений операторам
VAPID_PUBLIC_KEY = os.getenv("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.getenv("VAPID_PRIVATE_KEY", "")
VAPID_CLAIMS_EMAIL = os.getenv("VAPID_CLAIMS_EMAIL", "mailto:admin@profi-cpr.ru")

# DRF / JWT
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",  # Для UI запросов из браузера
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    # Защита от утечки информации через ошибки API
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Throttling для phonebridge hot endpoints. ScopedRateThrottle
    # смотрит на throttle_scope во view и применяет соответствующий rate.
    "DEFAULT_THROTTLE_CLASSES": [],
    "DEFAULT_THROTTLE_RATES": {
        "phone_pull": os.getenv("PHONE_PULL_RATE", "120/min"),
        "phone_heartbeat": os.getenv("PHONE_HEARTBEAT_RATE", "30/min"),
        "phone_telemetry": os.getenv("PHONE_TELEMETRY_RATE", "20/min"),
        # F9 (2026-04-18): auto-update check из CRMProfiDialer.
        # Ожидаемая частота: раз в несколько часов. 10/min с запасом.
        "mobile_app_latest": os.getenv("MOBILE_APP_LATEST_RATE", "10/min"),
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "ProfiCRM API",
    "DESCRIPTION": "REST API для ProfiCRM. Аутентификация: JWT Bearer token.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,  # Не включать /api/schema/ в сам schema
    # Swagger UI доступен только в DEBUG режиме (защита от exposure в production)
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
}

# Настройки JWT (simplejwt). Подобраны безопасные дефолты без изменения текущей логики API.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
}

# Frontend dev CORS (Vite)
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:5173").split(",") if o.strip()]

# Проверка: в production CORS_ALLOWED_ORIGINS не должен содержать localhost
if not DEBUG:
    localhost_origins = [o for o in CORS_ALLOWED_ORIGINS if "localhost" in o.lower() or "127.0.0.1" in o.lower()]
    if localhost_origins:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            f"CORS_ALLOWED_ORIGINS contains localhost origins in production: {localhost_origins}. "
            "Set CORS_ALLOWED_ORIGINS to your production domain(s) only."
        )

CORS_ALLOW_CREDENTIALS = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Upload limits (bytes). Default: 20MB total/request and 20MB per-file in memory.
# Real per-file limit is validated in forms/models where needed.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE", str(20 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE", str(20 * 1024 * 1024)))

# Кеш для rate limiting и защиты от брутфорса
# Используем Redis для production, LocMemCache для development
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
if REDIS_URL and not DEBUG:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
                "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                "IGNORE_EXCEPTIONS": True,  # Не падать, если Redis недоступен
            },
            "KEY_PREFIX": "crm",
            "TIMEOUT": 300,  # 5 минут по умолчанию
        }
    }
else:
    # Для development используем локальный кеш
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# Django Channels — WebSocket support for messenger real-time
if REDIS_URL and not DEBUG:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
                "prefix": "crm:ws",
                "capacity": 1500,
                "expiry": 60,
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }

# Celery Configuration
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/1")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/2")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 минут максимум на задачу
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 минут мягкий лимит
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Не брать задачи заранее
CELERY_TASK_ACKS_LATE = True  # Подтверждать задачи после выполнения
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # Исправление предупреждения о broker_connection_retry
CELERY_WORKER_HIJACK_ROOT_LOGGER = False  # Не перехватывать root logger
CELERY_WORKER_LOG_COLOR = False  # Отключить цветной вывод в логах
# Примечание: запуск Celery от root в Docker контейнере безопасен, так как контейнер изолирован
# Предупреждение о root user можно игнорировать в Docker окружении

# Поиск компаний: только PostgreSQL FTS+pg_trgm (CompanySearchIndex).
# SEARCH_ENGINE_BACKEND оставлен для обратной совместимости, но поддерживает только значение "postgres".
SEARCH_ENGINE_BACKEND = "postgres"

# Текстовый поиск: отсечка мусора и пороги (опционально через env, дефолты — без обязательного .env).
# ABS_MIN_SCORE: минимальный score для попадания в выдачу (абсолютный порог).
# RELATIVE_MIN_FACTOR: доля от top_score (0..1): результаты с score < top_score * factor отсекаются.
# EXACT_CUTOFF_LIMIT: при точном/фразовом совпадении по plain_text/t_name, если найдено <= N записей — вернуть только их.
# SIMILARITY_ONLY_IF_FTS_EMPTY: включать pg_trgm similarity fallback только когда FTS дал мало результатов (< 5).
def _float_env(name: str, default: float) -> float:
    try:
        v = os.getenv(name)
        return float(v) if v not in (None, "") else default
    except (TypeError, ValueError):
        return default

SEARCH_TEXT_ABS_MIN_SCORE = _float_env("SEARCH_TEXT_ABS_MIN_SCORE", 0.5)
SEARCH_TEXT_RELATIVE_MIN_FACTOR = _float_env("SEARCH_TEXT_RELATIVE_MIN_FACTOR", 0.15)
SEARCH_TEXT_EXACT_CUTOFF_LIMIT = int(os.getenv("SEARCH_TEXT_EXACT_CUTOFF_LIMIT", "20") or "20")
SEARCH_TEXT_SIMILARITY_ONLY_IF_FTS_EMPTY = (os.getenv("SEARCH_TEXT_SIMILARITY_ONLY_IF_FTS_EMPTY", "1") or "1").strip().lower() in ("1", "true", "yes")
SEARCH_TEXT_SIMILARITY_THRESHOLD = _float_env("SEARCH_TEXT_SIMILARITY_THRESHOLD", 0.4)

# Celery Beat Schedule (периодические задачи)
# Частота синхронизации квоты smtp.bz (сек). По умолчанию раз в 5 минут.
SMTP_BZ_QUOTA_SYNC_SECONDS = float(os.getenv("SMTP_BZ_QUOTA_SYNC_SECONDS", "300") or "300")
# Частота синхронизации отписок smtp.bz (сек). По умолчанию раз в 10 минут.
SMTP_BZ_UNSUB_SYNC_SECONDS = float(os.getenv("SMTP_BZ_UNSUB_SYNC_SECONDS", "600") or "600")
# Частота синхронизации статусов доставки smtp.bz (bounce/return/cancel) (сек). По умолчанию раз в 10 минут.
SMTP_BZ_DELIVERY_SYNC_SECONDS = float(os.getenv("SMTP_BZ_DELIVERY_SYNC_SECONDS", "600") or "600")
# Частота reconcile очереди рассылок (сек). По умолчанию раз в 5 минут.
MAILER_QUEUE_RECONCILE_SECONDS = float(os.getenv("MAILER_QUEUE_RECONCILE_SECONDS", "300") or "300")

# Retention policy: срок хранения записей в журналах (дни)
ACTIVITY_EVENT_RETENTION_DAYS = int(os.getenv("ACTIVITY_EVENT_RETENTION_DAYS", "180") or "180")
ERRORLOG_RETENTION_DAYS = int(os.getenv("ERRORLOG_RETENTION_DAYS", "90") or "90")
NOTIFICATION_RETENTION_DAYS = int(os.getenv("NOTIFICATION_RETENTION_DAYS", "90") or "90")

CELERY_BEAT_SCHEDULE = {
    "send-pending-emails": {
        "task": "mailer.tasks.send_pending_emails",
        "schedule": 60.0,  # Каждую минуту
    },
    "sync-smtp-bz-quota": {
        "task": "mailer.tasks.sync_smtp_bz_quota",
        "schedule": SMTP_BZ_QUOTA_SYNC_SECONDS,
    },
    "sync-smtp-bz-unsubscribes": {
        "task": "mailer.tasks.sync_smtp_bz_unsubscribes",
        "schedule": SMTP_BZ_UNSUB_SYNC_SECONDS,
    },
    "sync-smtp-bz-delivery-events": {
        "task": "mailer.tasks.sync_smtp_bz_delivery_events",
        "schedule": SMTP_BZ_DELIVERY_SYNC_SECONDS,
    },
    "reconcile-mail-campaign-queue": {
        "task": "mailer.tasks.reconcile_campaign_queue",
        "schedule": MAILER_QUEUE_RECONCILE_SECONDS,
    },
    "clean-old-call-requests": {
        "task": "phonebridge.tasks.clean_old_call_requests",
        "schedule": 3600.0,  # Каждый час
    },
    "reindex-companies-daily": {
        "task": "companies.tasks.reindex_companies_daily",
        "schedule": crontab(hour=0, minute=0),  # Ежедневно 00:00 (по CELERY_TIMEZONE = Europe/Moscow)
    },
    "generate-recurring-tasks": {
        "task": "tasksapp.tasks.generate_recurring_tasks",
        "schedule": crontab(hour=6, minute=0),  # Ежедневно 06:00 по Moscow
    },
    # Ежедневная генерация напоминаний о приближении окончания договоров.
    # Логика вынесена из context_processors.notifications_panel, чтобы не
    # писать в БД из GET-запросов (poll колокольчика).
    "generate-contract-reminders": {
        "task": "notifications.tasks.generate_contract_reminders",
        "schedule": crontab(hour=6, minute=30),
    },
    # Retention: еженедельно в воскресенье 03:00 MSK
    "purge-old-activity-events": {
        "task": "audit.tasks.purge_old_activity_events",
        "schedule": crontab(hour=3, minute=0, day_of_week=0),
    },
    "purge-old-error-logs": {
        "task": "audit.tasks.purge_old_error_logs",
        "schedule": crontab(hour=3, minute=15, day_of_week=0),
    },
    "purge-old-notifications": {
        "task": "notifications.tasks.purge_old_notifications",
        "schedule": crontab(hour=3, minute=30, day_of_week=0),
    },
    # Messenger: auto-resolve неактивных диалогов (каждые 15 минут)
    "messenger-auto-resolve": {
        "task": "messenger.tasks.auto_resolve_conversations",
        "schedule": 900.0,  # 15 минут
    },
    # Messenger: эскалация зависших диалогов (каждые 2 минуты)
    "messenger-escalate-stalled": {
        "task": "messenger.tasks.escalate_stalled_conversations",
        "schedule": 120.0,  # 2 минуты
    },
    # Messenger: эскалация молчаливых диалогов по waiting_minutes (каждые 30 сек)
    "messenger-escalate-waiting": {
        "task": "messenger.escalate_waiting_conversations",
        "schedule": 30.0,
    },
    # Messenger: перевод операторов в offline по таймауту heartbeat (каждую минуту)
    "messenger-check-offline-operators": {
        "task": "messenger.check_offline_operators",
        "schedule": 60.0,
    },
}

# Логирование
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "json": {
            "()": "core.json_formatter.JSONFormatter",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "request_id": {
            "()": "core.request_id.RequestIdLoggingFilter",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO" if not DEBUG else "DEBUG",
            "class": "logging.StreamHandler",
            # ENTERPRISE: JSON formatter в production для structured logging
            "formatter": "json" if not DEBUG else "verbose",
            "filters": ["request_id"],
        },
        **(
            {
                "file": {
                    "level": "INFO",
                    "class": "logging.handlers.RotatingFileHandler",
                    "filename": str(LOGS_DIR / "crm.log"),
                    "maxBytes": 10 * 1024 * 1024,  # 10 MB
                    "backupCount": 5,
                    "formatter": "verbose",
                    "filters": ["require_debug_false"],
                },
            }
            if _use_file_logging
            else {}
        ),
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": (["console", "file"] if _use_file_logging else ["console"]) if not DEBUG else ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": (["console", "file"] if _use_file_logging else ["console"]) if not DEBUG else ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "crm": {
            "handlers": (["console", "file"] if _use_file_logging else ["console"]) if not DEBUG else ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "mailer": {
            "handlers": (["console", "file"] if _use_file_logging else ["console"]) if not DEBUG else ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # ENTERPRISE: JSON formatter для mailer в production (structured logging)
        "mailer.tasks": {
            "handlers": (["console", "file"] if _use_file_logging else ["console"]) if not DEBUG else ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "phonebridge": {
            "handlers": (["console", "file"] if _use_file_logging else ["console"]) if not DEBUG else ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],  # Celery логирует только в консоль (Docker logs)
            "level": "INFO",
            "propagate": False,
        },
        "messenger": {
            "handlers": (["console", "file"] if _use_file_logging else ["console"]) if not DEBUG else ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "messenger.security": {
            "handlers": (["console", "file"] if _use_file_logging else ["console"]) if not DEBUG else ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "messenger.ws": {
            "handlers": (["console", "file"] if _use_file_logging else ["console"]) if not DEBUG else ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "messenger.tasks": {
            "handlers": (["console", "file"] if _use_file_logging else ["console"]) if not DEBUG else ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Явно задаём тип авто-поля для всех моделей проекта.
# Это предотвращает предупреждение вида:
# "Your models in app(s) ... have changes that are not yet reflected in a migration"
# когда миграции создавались с BigAutoField, а настройка отсутствовала.
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================================================
# ENTERPRISE: Mailer configuration (конфигурируемые лимиты)
# ============================================================================

# Throttling rates (запросов в час на пользователя)
MAILER_THROTTLE_CAMPAIGN_START_PER_HOUR = int(os.getenv("MAILER_THROTTLE_CAMPAIGN_START_PER_HOUR", "10"))
MAILER_THROTTLE_TEST_EMAIL_PER_HOUR = int(os.getenv("MAILER_THROTTLE_TEST_EMAIL_PER_HOUR", "5"))

# Circuit breaker threshold (количество последовательных transient ошибок до паузы)
MAILER_CIRCUIT_BREAKER_THRESHOLD = int(os.getenv("MAILER_CIRCUIT_BREAKER_THRESHOLD", "10"))

# Retry delay для transient errors (минуты)
MAILER_TRANSIENT_RETRY_DELAY_MINUTES = int(os.getenv("MAILER_TRANSIENT_RETRY_DELAY_MINUTES", "5"))

# PII logging policy
# "INFO" - только domain/masked/hash в INFO
# "WARNING" - можно masked в WARNING+
# "ERROR" - можно masked в ERROR+
MAILER_LOG_PII_LEVEL = os.getenv("MAILER_LOG_PII_LEVEL", "ERROR")

# Разрешить полный email в DEBUG логах (только для отладки)
MAILER_LOG_FULL_EMAILS = os.getenv("MAILER_LOG_FULL_EMAILS", "False").lower() == "true"

# Соль для хэширования email в логах
# ⚠️ ВАЖНО: Дефолтный salt НЕ должен использоваться в production!
# Установите уникальный MAILER_LOG_HASH_SALT через environment variable.
# Генерация: openssl rand -hex 32
_DEFAULT_LOG_HASH_SALT = "default-salt-change-in-production"
MAILER_LOG_HASH_SALT = os.getenv("MAILER_LOG_HASH_SALT", _DEFAULT_LOG_HASH_SALT)
if not DEBUG and MAILER_LOG_HASH_SALT == _DEFAULT_LOG_HASH_SALT:
    raise ImproperlyConfigured(
        "MAILER_LOG_HASH_SALT is using the default value in production. "
        "Set a unique salt in .env to protect email masking in logs. "
        "Generate: openssl rand -hex 32"
    )

# Custom test runner: при тестах на SQLite игнорирует PostgreSQL-специфичный синтаксис
# (GIN/trigram/tsvector индексы, расширения, триггеры). На PostgreSQL — стандартный DiscoverRunner.
TEST_RUNNER = "core.test_runner.SQLiteCompatibleTestRunner"
