from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("api/dashboard/poll/", views.dashboard_poll, name="dashboard_poll"),
    path("api/dashboard/sse/", views.dashboard_sse, name="dashboard_sse"),
    path("analytics/", views.analytics, name="analytics"),
    path("analytics/users/<int:user_id>/", views.analytics_user, name="analytics_user"),
    path("help/", views.help_page, name="help"),
    path("preferences/", views.preferences, name="preferences"),
    path("preferences/ui/", views.preferences_ui, name="preferences_ui"),
    path("preferences/ui/company-detail-view-mode/", views.preferences_company_detail_view_mode, name="preferences_company_detail_view_mode"),
    path("preferences/mail/", views.preferences_mail, name="preferences_mail"),
    path("reports/cold-calls/day/", views.cold_calls_report_day, name="cold_calls_report_day"),
    path("reports/cold-calls/month/", views.cold_calls_report_month, name="cold_calls_report_month"),
    path("reports/cold-calls/last-7-days/", views.cold_calls_report_last_7_days, name="cold_calls_report_last_7_days"),
    path("companies/", views.company_list, name="company_list"),
    path("companies/ajax/", views.company_list_ajax, name="company_list_ajax"),
    path("companies/autocomplete/", views.company_autocomplete, name="company_autocomplete"),
    path("companies/duplicates/", views.company_duplicates, name="company_duplicates"),
    path("companies/export/", views.company_export, name="company_export"),
    path("companies/bulk-transfer/preview/", views.company_bulk_transfer_preview, name="company_bulk_transfer_preview"),
    path("companies/bulk-transfer/", views.company_bulk_transfer, name="company_bulk_transfer"),
    path("companies/new/", views.company_create, name="company_create"),
    path("companies/<uuid:company_id>/", views.company_detail, name="company_detail"),
    path("companies/<uuid:company_id>/edit/", views.company_edit, name="company_edit"),
    path("companies/<uuid:company_id>/tasks/history/", views.company_tasks_history, name="company_tasks_history"),
    path("companies/<uuid:company_id>/update/", views.company_update, name="company_update"),
    path("companies/<uuid:company_id>/inline/", views.company_inline_update, name="company_inline_update"),
    path("companies/<uuid:company_id>/main-phone/update/", views.company_main_phone_update, name="company_main_phone_update"),
    path("companies/<uuid:company_id>/main-email/update/", views.company_main_email_update, name="company_main_email_update"),
    path("companies/<uuid:company_id>/contract/update/", views.company_contract_update, name="company_contract_update"),
    path("companies/<uuid:company_id>/cold-call/toggle/", views.company_cold_call_toggle, name="company_cold_call_toggle"),
    path("companies/<uuid:company_id>/cold-call/reset/", views.company_cold_call_reset, name="company_cold_call_reset"),
    path("companies/<uuid:company_id>/transfer/", views.company_transfer, name="company_transfer"),
    path("companies/<uuid:company_id>/delete-request/", views.company_delete_request_create, name="company_delete_request_create"),
    path("companies/<uuid:company_id>/delete-request/<int:req_id>/cancel/", views.company_delete_request_cancel, name="company_delete_request_cancel"),
    path("companies/<uuid:company_id>/delete-request/<int:req_id>/approve/", views.company_delete_request_approve, name="company_delete_request_approve"),
    path("companies/<uuid:company_id>/delete/", views.company_delete_direct, name="company_delete_direct"),
    path("companies/<uuid:company_id>/contacts/new/", views.contact_create, name="contact_create"),
    path("contacts/<uuid:contact_id>/edit/", views.contact_edit, name="contact_edit"),
    path("contacts/<uuid:contact_id>/delete/", views.contact_delete, name="contact_delete"),
    path("contacts/<uuid:contact_id>/cold-call/toggle/", views.contact_cold_call_toggle, name="contact_cold_call_toggle"),
    path("contacts/<uuid:contact_id>/cold-call/reset/", views.contact_cold_call_reset, name="contact_cold_call_reset"),
    path("contact-phones/<int:contact_phone_id>/cold-call/toggle/", views.contact_phone_cold_call_toggle, name="contact_phone_cold_call_toggle"),
    path("contact-phones/<int:contact_phone_id>/cold-call/reset/", views.contact_phone_cold_call_reset, name="contact_phone_cold_call_reset"),
    path("contact-phones/<int:contact_phone_id>/comment/", views.contact_phone_comment_update, name="contact_phone_comment_update"),
    path("company-phones/<int:company_phone_id>/cold-call/toggle/", views.company_phone_cold_call_toggle, name="company_phone_cold_call_toggle"),
    path("company-phones/<int:company_phone_id>/cold-call/reset/", views.company_phone_cold_call_reset, name="company_phone_cold_call_reset"),
    path("company-phones/<int:company_phone_id>/comment/", views.company_phone_comment_update, name="company_phone_comment_update"),
    path("company-phones/<int:company_phone_id>/update/", views.company_phone_value_update, name="company_phone_value_update"),
    path("companies/<uuid:company_id>/phones/create/", views.company_phone_create, name="company_phone_create"),
    path("companies/<uuid:company_id>/main-phone/comment/", views.company_main_phone_comment_update, name="company_main_phone_comment_update"),
    path("company-emails/<int:company_email_id>/update/", views.company_email_value_update, name="company_email_value_update"),
    path("companies/<uuid:company_id>/notes/add/", views.company_note_add, name="company_note_add"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/edit/", views.company_note_edit, name="company_note_edit"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/delete/", views.company_note_delete, name="company_note_delete"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/pin/", views.company_note_pin_toggle, name="company_note_pin_toggle"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/file/open/", views.company_note_attachment_open, name="company_note_attachment_open"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/file/download/", views.company_note_attachment_download, name="company_note_attachment_download"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/attachments/<int:attachment_id>/open/", views.company_note_attachment_by_id_open, name="company_note_attachment_by_id_open"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/attachments/<int:attachment_id>/download/", views.company_note_attachment_by_id_download, name="company_note_attachment_by_id_download"),
    path("companies/<uuid:company_id>/deals/add/", views.company_deal_add, name="company_deal_add"),
    path("companies/<uuid:company_id>/deals/<int:deal_id>/delete/", views.company_deal_delete, name="company_deal_delete"),
    path("phone/call/", views.phone_call_create, name="phone_call_create"),
    path("tasks/", views.task_list, name="task_list"),
    path("tasks/bulk-reassign/", views.task_bulk_reassign, name="task_bulk_reassign"),
    path("tasks/bulk-reschedule/", views.task_bulk_reschedule, name="task_bulk_reschedule"),
    path("tasks/bulk-reschedule/preview/", views.task_bulk_reschedule_preview, name="task_bulk_reschedule_preview"),
    path("tasks/bulk-reschedule/undo/<uuid:event_id>/", views.task_bulk_reschedule_undo, name="task_bulk_reschedule_undo"),
    path("tasks/new/", views.task_create, name="task_create"),
    path("tasks/<uuid:task_id>/", views.task_view, name="task_view"),
    path("tasks/<uuid:task_id>/edit/", views.task_edit, name="task_edit"),
    path("tasks/<uuid:task_id>/status/", views.task_set_status, name="task_set_status"),
    path("tasks/<uuid:task_id>/delete/", views.task_delete, name="task_delete"),

    # Messenger (операторская панель диалогов)
    path("messenger/conversations/", views.messenger_conversation_list, name="messenger_conversation_list"),
    path("messenger/conversations/<int:conversation_id>/", views.messenger_conversation_detail, name="messenger_conversation_detail"),

    # Settings (admin only)
    path("settings/", views.settings_dashboard, name="settings_dashboard"),
    path("settings/access/", views.settings_access, name="settings_access"),
    path("settings/access/roles/<str:role>/", views.settings_access_role, name="settings_access_role"),
    # Режим "просмотр как" (админ может визуально переключаться под роль/филиал)
    path("settings/view-as/", views.view_as_update, name="view_as_update"),
    path("settings/view-as/reset/", views.view_as_reset, name="view_as_reset"),
    path("settings/branches/", views.settings_branches, name="settings_branches"),
    path("settings/branches/new/", views.settings_branch_create, name="settings_branch_create"),
    path("settings/branches/<int:branch_id>/edit/", views.settings_branch_edit, name="settings_branch_edit"),
    path("settings/users/", views.settings_users, name="settings_users"),
    path("settings/users/new/", views.settings_user_create, name="settings_user_create"),
    path("settings/users/<int:user_id>/edit/", views.settings_user_edit, name="settings_user_edit"),
    path("settings/users/<int:user_id>/magic-link/generate/", views.settings_user_magic_link_generate, name="settings_user_magic_link_generate"),
    path("settings/users/<int:user_id>/logout/", views.settings_user_logout, name="settings_user_logout"),
    path("settings/users/<int:user_id>/form/", views.settings_user_form_ajax, name="settings_user_form_ajax"),
    path("settings/users/<int:user_id>/update/", views.settings_user_update_ajax, name="settings_user_update_ajax"),
    path("settings/dicts/", views.settings_dicts, name="settings_dicts"),
    path("settings/dicts/company-status/new/", views.settings_company_status_create, name="settings_company_status_create"),
    path("settings/dicts/company-status/<int:status_id>/edit/", views.settings_company_status_edit, name="settings_company_status_edit"),
    path("settings/dicts/company-status/<int:status_id>/delete/", views.settings_company_status_delete, name="settings_company_status_delete"),
    path("settings/dicts/company-sphere/new/", views.settings_company_sphere_create, name="settings_company_sphere_create"),
    path("settings/dicts/company-sphere/<int:sphere_id>/edit/", views.settings_company_sphere_edit, name="settings_company_sphere_edit"),
    path("settings/dicts/company-sphere/<int:sphere_id>/delete/", views.settings_company_sphere_delete, name="settings_company_sphere_delete"),
    path("settings/dicts/contract-type/new/", views.settings_contract_type_create, name="settings_contract_type_create"),
    path("settings/dicts/contract-type/<int:contract_type_id>/edit/", views.settings_contract_type_edit, name="settings_contract_type_edit"),
    path("settings/dicts/contract-type/<int:contract_type_id>/delete/", views.settings_contract_type_delete, name="settings_contract_type_delete"),
    path("settings/dicts/task-type/new/", views.settings_task_type_create, name="settings_task_type_create"),
    path("settings/dicts/task-type/<int:task_type_id>/edit/", views.settings_task_type_edit, name="settings_task_type_edit"),
    path("settings/dicts/task-type/<int:task_type_id>/delete/", views.settings_task_type_delete, name="settings_task_type_delete"),
    path("settings/activity/", views.settings_activity, name="settings_activity"),
    path("settings/error-log/", views.settings_error_log, name="settings_error_log"),
    path("settings/error-log/<uuid:error_id>/details/", views.settings_error_log_details, name="settings_error_log_details"),
    path("settings/error-log/<uuid:error_id>/resolve/", views.settings_error_log_resolve, name="settings_error_log_resolve"),
    path("settings/error-log/<uuid:error_id>/unresolve/", views.settings_error_log_unresolve, name="settings_error_log_unresolve"),
    path("settings/import/", views.settings_import, name="settings_import"),
    path("settings/import/tasks/", views.settings_import_tasks, name="settings_import_tasks"),
    path("settings/amocrm/", views.settings_amocrm, name="settings_amocrm"),
    path("settings/amocrm/callback/", views.settings_amocrm_callback, name="settings_amocrm_callback"),
    path("settings/amocrm/disconnect/", views.settings_amocrm_disconnect, name="settings_amocrm_disconnect"),
    path("settings/amocrm/migrate/progress/", views.settings_amocrm_migrate_progress, name="settings_amocrm_migrate_progress"),
    path("settings/amocrm/migrate/", views.settings_amocrm_migrate, name="settings_amocrm_migrate"),
    path("settings/amocrm/contacts-dry-run/", views.settings_amocrm_contacts_dry_run, name="settings_amocrm_contacts_dry_run"),
    path("settings/amocrm/debug-contacts/", views.settings_amocrm_debug_contacts, name="settings_amocrm_debug_contacts"),
    path("settings/company-columns/", views.settings_company_columns, name="settings_company_columns"),
    path("settings/security/", views.settings_security, name="settings_security"),
    path("settings/mobile/overview/", views.settings_mobile_overview, name="settings_mobile_overview"),
    path("settings/mobile/devices/", views.settings_mobile_devices, name="settings_mobile_devices"),
    path("settings/mobile/devices/<uuid:pk>/", views.settings_mobile_device_detail, name="settings_mobile_device_detail"),
    path("settings/calls/stats/", views.settings_calls_stats, name="settings_calls_stats"),
    path("settings/calls/stats/<int:user_id>/", views.settings_calls_manager_detail, name="settings_calls_manager_detail"),
    
    # Messenger settings (admin only)
    path("settings/messenger/", views.settings_messenger_overview, name="settings_messenger_overview"),
    path("settings/messenger/inboxes/new/", views.settings_messenger_inbox_edit, name="settings_messenger_inbox_create"),
    path("settings/messenger/inboxes/<int:inbox_id>/", views.settings_messenger_inbox_edit, name="settings_messenger_inbox_edit"),
    path("settings/messenger/routing/", views.settings_messenger_routing_list, name="settings_messenger_routing_list"),
    path("settings/messenger/routing/new/", views.settings_messenger_routing_edit, name="settings_messenger_routing_create"),
    path("settings/messenger/routing/<int:rule_id>/", views.settings_messenger_routing_edit, name="settings_messenger_routing_edit"),
    path("settings/messenger/routing/<int:rule_id>/delete/", views.settings_messenger_routing_delete, name="settings_messenger_routing_delete"),
    
    # Мобильное приложение
    path("mobile-app/", views.mobile_app_page, name="mobile_app_page"),
    path("mobile-app/download/<uuid:build_id>/", views.mobile_app_download, name="mobile_app_download"),
    path("mobile-app/qr.png", views.mobile_app_qr_image, name="mobile_app_qr_image"),
]


