from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("api/dashboard/poll/", views.dashboard_poll, name="dashboard_poll"),
    path("analytics/", views.analytics, name="analytics"),
    path("analytics/users/<int:user_id>/", views.analytics_user, name="analytics_user"),
    path("help/", views.help_page, name="help"),
    path("settings/", views.preferences, name="preferences"),
    path("settings/ui/", views.preferences_ui, name="preferences_ui"),
    path("settings/ui/company-detail-view-mode/", views.preferences_company_detail_view_mode, name="preferences_company_detail_view_mode"),
    path("settings/ui/v2-scale/", views.preferences_v2_scale, name="preferences_v2_scale"),
    path("settings/mail/", views.preferences_mail, name="preferences_mail"),
    path("settings/profile/", views.preferences_profile, name="preferences_profile"),
    path("settings/password/", views.preferences_password, name="preferences_password"),
    # F5: личный учёт отсутствия (отпуск/больничный/отгул)
    path("settings/absence/create/", views.preferences_absence_create, name="preferences_absence_create"),
    path("settings/absence/<int:absence_id>/delete/", views.preferences_absence_delete, name="preferences_absence_delete"),
    path("settings/mail-signature/", views.preferences_mail_signature, name="preferences_mail_signature"),
    path("settings/avatar/upload/", views.preferences_avatar_upload, name="preferences_avatar_upload"),
    path("settings/avatar/delete/", views.preferences_avatar_delete, name="preferences_avatar_delete"),
    path("settings/table-settings/", views.preferences_table_settings, name="preferences_table_settings"),
    path("reports/cold-calls/day/", views.cold_calls_report_day, name="cold_calls_report_day"),
    path("reports/cold-calls/month/", views.cold_calls_report_month, name="cold_calls_report_month"),
    path("reports/cold-calls/last-7-days/", views.cold_calls_report_last_7_days, name="cold_calls_report_last_7_days"),
    path("companies/", views.company_list, name="company_list"),
    path("companies/ajax/", views.company_list_ajax, name="company_list_ajax"),
    path("companies/autocomplete/", views.company_autocomplete, name="company_autocomplete"),
    path("companies/duplicates/", views.company_duplicates, name="company_duplicates"),
    path("companies/export/", views.company_export, name="company_export"),
    path("companies/bulk-transfer/preview/", views.company_bulk_transfer_preview, name="company_bulk_transfer_preview"),
    path("companies/bulk-transfer/", views.company_bulk_transfer, name="company_bulk_transfer"),
    path("companies/new/", views.company_create, name="company_create"),
    path("companies/<uuid:company_id>/", views.company_detail, name="company_detail"),
    path("companies/<uuid:company_id>/edit/", views.company_edit, name="company_edit"),
    path("companies/<uuid:company_id>/tasks/history/", views.company_tasks_history, name="company_tasks_history"),
    path("companies/<uuid:company_id>/update/", views.company_update, name="company_update"),
    path("companies/<uuid:company_id>/inline/", views.company_inline_update, name="company_inline_update"),
    path("companies/<uuid:company_id>/main-phone/update/", views.company_main_phone_update, name="company_main_phone_update"),
    path("companies/<uuid:company_id>/main-email/update/", views.company_main_email_update, name="company_main_email_update"),
    path("companies/<uuid:company_id>/contract/update/", views.company_contract_update, name="company_contract_update"),
    path("companies/<uuid:company_id>/cold-call/toggle/", views.company_cold_call_toggle, name="company_cold_call_toggle"),
    path("companies/<uuid:company_id>/cold-call/reset/", views.company_cold_call_reset, name="company_cold_call_reset"),
    path("companies/<uuid:company_id>/transfer/", views.company_transfer, name="company_transfer"),
    path("companies/<uuid:company_id>/delete-request/", views.company_delete_request_create, name="company_delete_request_create"),
    path("companies/<uuid:company_id>/delete-request/<int:req_id>/cancel/", views.company_delete_request_cancel, name="company_delete_request_cancel"),
    path("companies/<uuid:company_id>/delete-request/<int:req_id>/approve/", views.company_delete_request_approve, name="company_delete_request_approve"),
    path("companies/<uuid:company_id>/delete/", views.company_delete_direct, name="company_delete_direct"),
    path("companies/<uuid:company_id>/contacts/new/", views.contact_create, name="contact_create"),
    path("contacts/<uuid:contact_id>/edit/", views.contact_edit, name="contact_edit"),
    path("contacts/<uuid:contact_id>/delete/", views.contact_delete, name="contact_delete"),
    path("contacts/<uuid:contact_id>/cold-call/toggle/", views.contact_cold_call_toggle, name="contact_cold_call_toggle"),
    path("contacts/<uuid:contact_id>/cold-call/reset/", views.contact_cold_call_reset, name="contact_cold_call_reset"),
    path("contact-phones/<int:contact_phone_id>/cold-call/toggle/", views.contact_phone_cold_call_toggle, name="contact_phone_cold_call_toggle"),
    path("contact-phones/<int:contact_phone_id>/cold-call/reset/", views.contact_phone_cold_call_reset, name="contact_phone_cold_call_reset"),
    path("contact-phones/<int:contact_phone_id>/comment/", views.contact_phone_comment_update, name="contact_phone_comment_update"),
    path("company-phones/<int:company_phone_id>/cold-call/toggle/", views.company_phone_cold_call_toggle, name="company_phone_cold_call_toggle"),
    path("company-phones/<int:company_phone_id>/cold-call/reset/", views.company_phone_cold_call_reset, name="company_phone_cold_call_reset"),
    path("company-phones/<int:company_phone_id>/comment/", views.company_phone_comment_update, name="company_phone_comment_update"),
    path("company-phones/<int:company_phone_id>/update/", views.company_phone_value_update, name="company_phone_value_update"),
    path("companies/<uuid:company_id>/phones/create/", views.company_phone_create, name="company_phone_create"),
    path("companies/<uuid:company_id>/main-phone/comment/", views.company_main_phone_comment_update, name="company_main_phone_comment_update"),
    path("company-emails/<int:company_email_id>/update/", views.company_email_value_update, name="company_email_value_update"),
    path("companies/<uuid:company_id>/notes/add/", views.company_note_add, name="company_note_add"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/edit/", views.company_note_edit, name="company_note_edit"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/delete/", views.company_note_delete, name="company_note_delete"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/pin/", views.company_note_pin_toggle, name="company_note_pin_toggle"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/file/open/", views.company_note_attachment_open, name="company_note_attachment_open"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/file/download/", views.company_note_attachment_download, name="company_note_attachment_download"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/attachments/<int:attachment_id>/open/", views.company_note_attachment_by_id_open, name="company_note_attachment_by_id_open"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/attachments/<int:attachment_id>/download/", views.company_note_attachment_by_id_download, name="company_note_attachment_by_id_download"),
    path("companies/<uuid:company_id>/deals/add/", views.company_deal_add, name="company_deal_add"),
    path("companies/<uuid:company_id>/deals/<int:deal_id>/delete/", views.company_deal_delete, name="company_deal_delete"),
    path("phone/call/", views.phone_call_create, name="phone_call_create"),
    path("tasks/", views.task_list, name="task_list"),
    path("tasks/bulk-reassign/", views.task_bulk_reassign, name="task_bulk_reassign"),
    path("tasks/bulk-reschedule/", views.task_bulk_reschedule, name="task_bulk_reschedule"),
    path("tasks/bulk-reschedule/preview/", views.task_bulk_reschedule_preview, name="task_bulk_reschedule_preview"),
    path("tasks/bulk-reschedule/undo/<uuid:event_id>/", views.task_bulk_reschedule_undo, name="task_bulk_reschedule_undo"),
    path("tasks/new/", views.task_create, name="task_create"),
    path("tasks/v2/new/partial/", views.task_create_v2_partial, name="ui_v2_task_create_partial"),
    path("tasks/v2/<uuid:task_id>/partial/", views.task_view_v2_partial, name="ui_v2_task_view_partial"),
    path("tasks/v2/<uuid:task_id>/edit/partial/", views.task_edit_v2_partial, name="ui_v2_task_edit_partial"),
    path("tasks/<uuid:task_id>/", views.task_view, name="task_view"),
    path("tasks/<uuid:task_id>/edit/", views.task_edit, name="task_edit"),
    path("tasks/<uuid:task_id>/status/", views.task_set_status, name="task_set_status"),
    path("tasks/<uuid:task_id>/delete/", views.task_delete, name="task_delete"),
    path("tasks/<uuid:task_id>/comment/", views.task_add_comment, name="task_add_comment"),

    # Settings (admin only)
    path("admin/", views.settings_dashboard, name="settings_dashboard"),
    path("admin/announcements/", views.settings_announcements, name="settings_announcements"),
    path("admin/access/", views.settings_access, name="settings_access"),
    path("admin/access/roles/<str:role>/", views.settings_access_role, name="settings_access_role"),
    # F7 R1: ролевые KPI-дашборды v2 (MVP — MANAGER)
    path("analytics/v2/", views.analytics_v2_home, name="analytics_v2_home"),
    # F6 R1+R2: SMTP onboarding wizard + Fernet re-save UI + config edit
    path("admin/mail/setup/", views.settings_mail_setup, name="settings_mail_setup"),
    path("admin/mail/setup/save-password/", views.settings_mail_save_password, name="settings_mail_save_password"),
    path("admin/mail/setup/save-config/", views.settings_mail_save_config, name="settings_mail_save_config"),
    path("admin/mail/setup/toggle-enabled/", views.settings_mail_toggle_enabled, name="settings_mail_toggle_enabled"),
    path("admin/mail/setup/test-send/", views.settings_mail_test_send, name="settings_mail_test_send"),
    # Режим "просмотр как" (админ может визуально переключаться под роль/филиал)
    path("admin/view-as/", views.view_as_update, name="view_as_update"),
    path("admin/view-as/reset/", views.view_as_reset, name="view_as_reset"),
    path("admin/branches/", views.settings_branches, name="settings_branches"),
    path("admin/branches/new/", views.settings_branch_create, name="settings_branch_create"),
    path("admin/branches/<int:branch_id>/edit/", views.settings_branch_edit, name="settings_branch_edit"),
    path("admin/users/", views.settings_users, name="settings_users"),
    path("admin/users/new/", views.settings_user_create, name="settings_user_create"),
    path("admin/users/<int:user_id>/edit/", views.settings_user_edit, name="settings_user_edit"),
    path("admin/users/<int:user_id>/magic-link/generate/", views.settings_user_magic_link_generate, name="settings_user_magic_link_generate"),
    path("admin/users/<int:user_id>/logout/", views.settings_user_logout, name="settings_user_logout"),
    path("admin/users/<int:user_id>/form/", views.settings_user_form_ajax, name="settings_user_form_ajax"),
    path("admin/users/<int:user_id>/update/", views.settings_user_update_ajax, name="settings_user_update_ajax"),
    path("admin/users/<int:user_id>/delete/", views.settings_user_delete, name="settings_user_delete"),
    path("admin/dicts/", views.settings_dicts, name="settings_dicts"),
    path("admin/dicts/company-status/new/", views.settings_company_status_create, name="settings_company_status_create"),
    path("admin/dicts/company-status/<int:status_id>/edit/", views.settings_company_status_edit, name="settings_company_status_edit"),
    path("admin/dicts/company-status/<int:status_id>/delete/", views.settings_company_status_delete, name="settings_company_status_delete"),
    path("admin/dicts/company-sphere/new/", views.settings_company_sphere_create, name="settings_company_sphere_create"),
    path("admin/dicts/company-sphere/<int:sphere_id>/edit/", views.settings_company_sphere_edit, name="settings_company_sphere_edit"),
    path("admin/dicts/company-sphere/<int:sphere_id>/delete/", views.settings_company_sphere_delete, name="settings_company_sphere_delete"),
    path("admin/dicts/contract-type/new/", views.settings_contract_type_create, name="settings_contract_type_create"),
    path("admin/dicts/contract-type/<int:contract_type_id>/edit/", views.settings_contract_type_edit, name="settings_contract_type_edit"),
    path("admin/dicts/contract-type/<int:contract_type_id>/delete/", views.settings_contract_type_delete, name="settings_contract_type_delete"),
    path("admin/dicts/task-type/new/", views.settings_task_type_create, name="settings_task_type_create"),
    path("admin/dicts/task-type/<int:task_type_id>/edit/", views.settings_task_type_edit, name="settings_task_type_edit"),
    path("admin/dicts/task-type/<int:task_type_id>/delete/", views.settings_task_type_delete, name="settings_task_type_delete"),
    path("admin/activity/", views.settings_activity, name="settings_activity"),
    path("admin/error-log/", views.settings_error_log, name="settings_error_log"),
    path("admin/error-log/<uuid:error_id>/details/", views.settings_error_log_details, name="settings_error_log_details"),
    path("admin/error-log/<uuid:error_id>/resolve/", views.settings_error_log_resolve, name="settings_error_log_resolve"),
    path("admin/error-log/<uuid:error_id>/unresolve/", views.settings_error_log_unresolve, name="settings_error_log_unresolve"),
    path("admin/import/", views.settings_import, name="settings_import"),
    path("admin/import/tasks/", views.settings_import_tasks, name="settings_import_tasks"),
    path("admin/amocrm/", views.settings_amocrm, name="settings_amocrm"),
    path("admin/amocrm/callback/", views.settings_amocrm_callback, name="settings_amocrm_callback"),
    path("admin/amocrm/disconnect/", views.settings_amocrm_disconnect, name="settings_amocrm_disconnect"),
    path("admin/amocrm/migrate/progress/", views.settings_amocrm_migrate_progress, name="settings_amocrm_migrate_progress"),
    path("admin/amocrm/migrate/", views.settings_amocrm_migrate, name="settings_amocrm_migrate"),
    path("admin/amocrm/contacts-dry-run/", views.settings_amocrm_contacts_dry_run, name="settings_amocrm_contacts_dry_run"),
    path("admin/amocrm/debug-contacts/", views.settings_amocrm_debug_contacts, name="settings_amocrm_debug_contacts"),
    path("admin/company-columns/", views.settings_company_columns, name="settings_company_columns"),
    path("admin/security/", views.settings_security, name="settings_security"),
    path("admin/mobile/overview/", views.settings_mobile_overview, name="settings_mobile_overview"),
    path("admin/mobile/devices/", views.settings_mobile_devices, name="settings_mobile_devices"),
    path("admin/mobile/devices/<uuid:pk>/", views.settings_mobile_device_detail, name="settings_mobile_device_detail"),
    path("admin/calls/stats/", views.settings_calls_stats, name="settings_calls_stats"),
    path("admin/calls/stats/<int:user_id>/", views.settings_calls_manager_detail, name="settings_calls_manager_detail"),

    # Messenger settings (admin only)
    path("admin/messenger/", views.settings_messenger_overview, name="settings_messenger_overview"),
    path("admin/messenger/sources/choose/", views.settings_messenger_source_choose, name="settings_messenger_source_choose"),
    path("admin/messenger/inboxes/new/", views.settings_messenger_inbox_edit, name="settings_messenger_inbox_create"),
    path("admin/messenger/inboxes/<int:inbox_id>/", views.settings_messenger_inbox_edit, name="settings_messenger_inbox_edit"),
    path("admin/messenger/inboxes/<int:inbox_id>/ready/", views.settings_messenger_inbox_ready, name="settings_messenger_inbox_ready"),
    path("admin/messenger/routing/", views.settings_messenger_routing_list, name="settings_messenger_routing_list"),
    path("admin/messenger/routing/new/", views.settings_messenger_routing_edit, name="settings_messenger_routing_create"),
    path("admin/messenger/routing/<int:rule_id>/", views.settings_messenger_routing_edit, name="settings_messenger_routing_edit"),
    path("admin/messenger/routing/<int:rule_id>/delete/", views.settings_messenger_routing_delete, name="settings_messenger_routing_delete"),
    path("admin/messenger/health/", views.settings_messenger_health, name="settings_messenger_health"),
    path("admin/messenger/analytics/", views.settings_messenger_analytics, name="settings_messenger_analytics"),
    path("admin/messenger/canned-responses/", views.settings_messenger_canned_list, name="settings_messenger_canned_list"),
    path("admin/messenger/canned-responses/new/", views.settings_messenger_canned_edit, name="settings_messenger_canned_create"),
    path("admin/messenger/canned-responses/<int:response_id>/", views.settings_messenger_canned_edit, name="settings_messenger_canned_edit"),
    path("admin/messenger/canned-responses/<int:response_id>/delete/", views.settings_messenger_canned_delete, name="settings_messenger_canned_delete"),
    path("admin/messenger/campaigns/", views.settings_messenger_campaigns, name="settings_messenger_campaigns"),
    path("admin/messenger/automation/", views.settings_messenger_automation, name="settings_messenger_automation"),

    # Messenger operator panel
    path("messenger/", views.messenger_conversations_unified, name="messenger_conversations_unified"),
    path("messenger/me/status/", views.messenger_agent_status, name="messenger_agent_status"),

    # Мобильное приложение
    path("mobile-app/", views.mobile_app_page, name="mobile_app_page"),
    path("mobile-app/download/<uuid:build_id>/", views.mobile_app_download, name="mobile_app_download"),
    path("mobile-app/qr.png", views.mobile_app_qr_image, name="mobile_app_qr_image"),
]


