from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("analytics/", views.analytics, name="analytics"),
    path("analytics/users/<int:user_id>/", views.analytics_user, name="analytics_user"),
    path("reports/cold-calls/day/", views.cold_calls_report_day, name="cold_calls_report_day"),
    path("reports/cold-calls/month/", views.cold_calls_report_month, name="cold_calls_report_month"),
    path("companies/", views.company_list, name="company_list"),
    path("companies/duplicates/", views.company_duplicates, name="company_duplicates"),
    path("companies/export/", views.company_export, name="company_export"),
    path("companies/bulk-transfer/", views.company_bulk_transfer, name="company_bulk_transfer"),
    path("companies/new/", views.company_create, name="company_create"),
    path("companies/<uuid:company_id>/", views.company_detail, name="company_detail"),
    path("companies/<uuid:company_id>/edit/", views.company_edit, name="company_edit"),
    path("companies/<uuid:company_id>/update/", views.company_update, name="company_update"),
    path("companies/<uuid:company_id>/contract/update/", views.company_contract_update, name="company_contract_update"),
    path("companies/<uuid:company_id>/cold-call/toggle/", views.company_cold_call_toggle, name="company_cold_call_toggle"),
    path("companies/<uuid:company_id>/lead-state/request/", views.company_lead_state_request_create, name="company_lead_state_request_create"),
    path(
        "companies/<uuid:company_id>/lead-state/request/<uuid:req_id>/approve/",
        views.company_lead_state_request_approve,
        name="company_lead_state_request_approve",
    ),
    path(
        "companies/<uuid:company_id>/lead-state/request/<uuid:req_id>/cancel/",
        views.company_lead_state_request_cancel,
        name="company_lead_state_request_cancel",
    ),
    path("companies/<uuid:company_id>/lead-state/set/", views.company_lead_state_set, name="company_lead_state_set"),
    path("companies/<uuid:company_id>/transfer/", views.company_transfer, name="company_transfer"),
    path("companies/<uuid:company_id>/delete-request/", views.company_delete_request_create, name="company_delete_request_create"),
    path("companies/<uuid:company_id>/delete-request/<int:req_id>/cancel/", views.company_delete_request_cancel, name="company_delete_request_cancel"),
    path("companies/<uuid:company_id>/delete-request/<int:req_id>/approve/", views.company_delete_request_approve, name="company_delete_request_approve"),
    path("companies/<uuid:company_id>/delete/", views.company_delete_direct, name="company_delete_direct"),
    path("companies/<uuid:company_id>/contacts/new/", views.contact_create, name="contact_create"),
    path("contacts/<uuid:contact_id>/edit/", views.contact_edit, name="contact_edit"),
    path("contacts/<uuid:contact_id>/cold-call/toggle/", views.contact_cold_call_toggle, name="contact_cold_call_toggle"),
    path("companies/<uuid:company_id>/notes/add/", views.company_note_add, name="company_note_add"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/edit/", views.company_note_edit, name="company_note_edit"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/delete/", views.company_note_delete, name="company_note_delete"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/pin/", views.company_note_pin_toggle, name="company_note_pin_toggle"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/file/open/", views.company_note_attachment_open, name="company_note_attachment_open"),
    path("companies/<uuid:company_id>/notes/<int:note_id>/file/download/", views.company_note_attachment_download, name="company_note_attachment_download"),
    path("phone/call/", views.phone_call_create, name="phone_call_create"),
    path("tasks/", views.task_list, name="task_list"),
    path("tasks/new/", views.task_create, name="task_create"),
    path("tasks/<uuid:task_id>/status/", views.task_set_status, name="task_set_status"),

    # Settings (admin only)
    path("settings/", views.settings_dashboard, name="settings_dashboard"),
    path("settings/branches/", views.settings_branches, name="settings_branches"),
    path("settings/branches/new/", views.settings_branch_create, name="settings_branch_create"),
    path("settings/branches/<int:branch_id>/edit/", views.settings_branch_edit, name="settings_branch_edit"),
    path("settings/users/", views.settings_users, name="settings_users"),
    path("settings/users/new/", views.settings_user_create, name="settings_user_create"),
    path("settings/users/<int:user_id>/edit/", views.settings_user_edit, name="settings_user_edit"),
    path("settings/dicts/", views.settings_dicts, name="settings_dicts"),
    path("settings/dicts/company-status/new/", views.settings_company_status_create, name="settings_company_status_create"),
    path("settings/dicts/company-sphere/new/", views.settings_company_sphere_create, name="settings_company_sphere_create"),
    path("settings/dicts/task-type/new/", views.settings_task_type_create, name="settings_task_type_create"),
    path("settings/activity/", views.settings_activity, name="settings_activity"),
    path("settings/import/", views.settings_import, name="settings_import"),
    path("settings/import/tasks/", views.settings_import_tasks, name="settings_import_tasks"),
    path("settings/amocrm/", views.settings_amocrm, name="settings_amocrm"),
    path("settings/amocrm/callback/", views.settings_amocrm_callback, name="settings_amocrm_callback"),
    path("settings/amocrm/disconnect/", views.settings_amocrm_disconnect, name="settings_amocrm_disconnect"),
    path("settings/amocrm/migrate/", views.settings_amocrm_migrate, name="settings_amocrm_migrate"),
    path("settings/company-columns/", views.settings_company_columns, name="settings_company_columns"),
    path("settings/security/", views.settings_security, name="settings_security"),
]


