# Generated by Django 6.0 on 2025-12-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='is_cold_call',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
