# Generated by Django 6.0 on 2025-12-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebridge', '0002_callrequest_is_cold_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='call_duration_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность звонка (секунды)'),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='call_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала звонка'),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='call_status',
            field=models.CharField(blank=True, choices=[('connected', 'Дозвонился'), ('no_answer', 'Не дозвонился'), ('busy', 'Занято'), ('rejected', 'Отклонен'), ('missed', 'Пропущен')], db_index=True, max_length=16, null=True, verbose_name='Статус звонка'),
        ),
    ]
