# Generated by Django 6.0 on 2026-01-14

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("phonebridge", "0003_callrequest_call_duration_seconds_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="phonedevice",
            name="app_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="phonedevice",
            name="last_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="phonedevice",
            name="last_error_message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="phonedevice",
            name="last_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phonedevice",
            name="last_poll_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phonedevice",
            name="last_poll_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="phonedevice",
            index=models.Index(fields=["last_seen_at"], name="phonebridge_last_see_idx"),
        ),
        migrations.CreateModel(
            name="PhoneTelemetry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts", models.DateTimeField(verbose_name="Время события")),
                ("type", models.CharField(choices=[("latency", "Latency"), ("error", "Error"), ("auth", "Auth"), ("queue", "Queue"), ("other", "Other")], default="other", max_length=32, verbose_name="Тип")),
                ("endpoint", models.CharField(blank=True, default="", max_length=128, verbose_name="Endpoint")),
                ("http_code", models.IntegerField(blank=True, null=True, verbose_name="HTTP-код")),
                ("value_ms", models.IntegerField(blank=True, null=True, verbose_name="Значение (мс)")),
                ("extra", models.JSONField(blank=True, default=dict, verbose_name="Доп. данные")),
                ("device", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="telemetry", to="phonebridge.phonedevice")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="phone_telemetry", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-ts"],
            },
        ),
        migrations.CreateModel(
            name="PhoneLogBundle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts", models.DateTimeField(verbose_name="Время")),
                ("level_summary", models.CharField(blank=True, default="", max_length=64, verbose_name="Уровень")),
                ("source", models.CharField(blank=True, default="", max_length=64, verbose_name="Источник")),
                ("payload", models.TextField(verbose_name="Данные")),
                ("device", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="log_bundles", to="phonebridge.phonedevice")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="phone_log_bundles", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-ts"],
            },
        ),
        migrations.AddIndex(
            model_name="phonetelemetry",
            index=models.Index(fields=["user", "ts"], name="phonebridge_telemetry_user_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="phonetelemetry",
            index=models.Index(fields=["endpoint", "ts"], name="phonebridge_telemetry_ep_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="phonelogbundle",
            index=models.Index(fields=["user", "ts"], name="phonebridge_log_user_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="phonelogbundle",
            index=models.Index(fields=["source", "ts"], name="phonebridge_log_source_ts_idx"),
        ),
    ]

