# Generated by Django 6.0 on 2026-01-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebridge', '0007_add_call_analytics_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mobileappbuild',
            new_name='phonebridge_env_ac3dc6_idx',
            old_name='phonebridge_env_is_ac_upload_idx',
        ),
        migrations.RenameIndex(
            model_name='mobileappqrtoken',
            new_name='phonebridge_token_d78bf5_idx',
            old_name='phonebridge_token_idx',
        ),
        migrations.RenameIndex(
            model_name='mobileappqrtoken',
            new_name='phonebridge_user_id_43a6d6_idx',
            old_name='phonebridge_user_creat_idx',
        ),
        migrations.RenameIndex(
            model_name='mobileappqrtoken',
            new_name='phonebridge_expires_88a1ee_idx',
            old_name='phonebridge_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='phonedevice',
            new_name='phonebridge_last_se_a9839e_idx',
            old_name='phonebridge_last_see_idx',
        ),
        migrations.RenameIndex(
            model_name='phonelogbundle',
            new_name='phonebridge_user_id_9749ea_idx',
            old_name='phonebridge_log_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='phonelogbundle',
            new_name='phonebridge_source_edb9f8_idx',
            old_name='phonebridge_log_source_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='phonetelemetry',
            new_name='phonebridge_user_id_76c561_idx',
            old_name='phonebridge_telemetry_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='phonetelemetry',
            new_name='phonebridge_endpoin_eecea4_idx',
            old_name='phonebridge_telemetry_ep_ts_idx',
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='call_status',
            field=models.CharField(blank=True, choices=[('connected', 'Дозвонился'), ('no_answer', 'Не дозвонился'), ('busy', 'Занято'), ('rejected', 'Отклонен'), ('missed', 'Пропущен'), ('unknown', 'Не удалось определить')], db_index=True, max_length=16, null=True, verbose_name='Статус звонка'),
        ),
    ]
