# Generated by Django 6.0 on 2026-03-16 03:42

import phonebridge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebridge', '0008_rename_phonebridge_env_is_ac_upload_idx_phonebridge_env_ac3dc6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileappbuild',
            name='file',
            field=models.FileField(upload_to='mobile_apps/', validators=[phonebridge.models._validate_apk_extension], verbose_name='APK файл'),
        ),
    ]
