# Generated by Django 6.0 on 2026-04-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebridge', '0010_qr_token_hash'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mobileappqrtoken',
            name='phonebridge_token_d78bf5_idx',
        ),
    ]
