# Generated by Django 6.0 on 2026-01-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0007_task_company_due_status_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasksapp_task_company_due_status_idx',
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='color',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Иконка'),
        ),
    ]
