# Generated by Django 6.0 on 2026-03-15 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0011_alter_taskcomment_id_alter_taskevent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_recurring_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_instances', to='tasksapp.task', verbose_name='Родительская задача (повтор)'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_next_generate_after',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующая генерация после'),
        ),
    ]
