# Generated by Django 6.0 on 2025-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UiGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_list_columns', models.JSONField(blank=True, default=list, verbose_name='Колонки списка компаний')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки интерфейса',
                'verbose_name_plural': 'Настройки интерфейса',
            },
        ),
    ]
