# Generated by Django 6.0 on 2025-12-16 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_branch_code_alter_branch_name_and_more'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='amocrm_company_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID компании (amo)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='accounts.branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Юр. название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='raw_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырые поля (импорт)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='company',
            name='spheres',
            field=models.ManyToManyField(blank=True, related_name='companies', to='companies.companysphere', verbose_name='Сферы'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.companystatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='companynote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='companynote',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companynote',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='companysphere',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='companystatus',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='amocrm_contact_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID контакта (amo)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='raw_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырые поля (импорт)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='companies.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='value',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='companies.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='value',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Телефон'),
        ),
    ]
