# Generated by Django 6.0 on 2025-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_company_deletion_requests'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companydeletionrequest',
            new_name='companies_c_company_d1c75d_idx',
            old_name='companies_co_company__f24e1e_idx',
        ),
        migrations.RenameIndex(
            model_name='companydeletionrequest',
            new_name='companies_c_status_4459b9_idx',
            old_name='companies_co_status__514c62_idx',
        ),
        migrations.AddField(
            model_name='companynote',
            name='edited_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Редактировано'),
        ),
    ]
