# Generated by Django 6.0 on 2025-12-23 12:16

from django.db import migrations, models


def _copy_company_cold_call_to_primary(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    # Раньше отметка была на всю компанию. Переносим в "основной контакт".
    Company.objects.filter(is_cold_call=True).update(primary_contact_is_cold_call=True)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_companynote_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='primary_contact_is_cold_call',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Холодный звонок (основной контакт)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_cold_call',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Холодный звонок'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_cold_call',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Холодный звонок (устар.)'),
        ),
        migrations.RunPython(_copy_company_cold_call_to_primary, migrations.RunPython.noop),
    ]
