# Generated by Django 6.0 on 2025-12-23 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_company_primary_contact_is_cold_call_and_more'),
        ('phonebridge', '0002_callrequest_is_cold_call'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='primary_cold_marked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Холодный (осн. контакт): когда отметили'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_cold_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cold_marks', to=settings.AUTH_USER_MODEL, verbose_name='Холодный (осн. контакт): кто отметил'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_cold_marked_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phonebridge.callrequest', verbose_name='Холодный (осн. контакт): звонок'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cold_marked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Холодный: когда отметили'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cold_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_cold_marks', to=settings.AUTH_USER_MODEL, verbose_name='Холодный: кто отметил'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cold_marked_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phonebridge.callrequest', verbose_name='Холодный: звонок'),
        ),
    ]
