# Generated by Django 6.0 on 2025-12-23 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_company_primary_cold_marked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lead_state',
            field=models.CharField(choices=[('cold', 'Холодная'), ('warm', 'Тёплая')], db_index=True, default='cold', help_text='Холодная/тёплая карточка (влияет на доступность отметок «холодный звонок»).', max_length=8, verbose_name='Состояние карточки'),
        ),
        migrations.CreateModel(
            name='CompanyLeadStateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_state', models.CharField(choices=[('cold', 'Холодная'), ('warm', 'Тёплая')], max_length=8, verbose_name='Запрошенное состояние')),
                ('note', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Подтверждено'), ('cancelled', 'Отклонено')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('decision_note', models.TextField(blank=True, default='', verbose_name='Комментарий решения')),
                ('decided_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Когда решили')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_state_requests', to='companies.company', verbose_name='Компания')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_state_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Кто решил')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_state_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто запросил')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'status', 'created_at'], name='companies_c_company_40270f_idx'), models.Index(fields=['status', 'created_at'], name='companies_c_status_71f79d_idx')],
            },
        ),
    ]
