# Generated by Django 6.0 on 2025-12-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_company_lead_state_companyleadstaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='lead_state',
            field=models.CharField(choices=[('cold', 'Холодная'), ('warm', 'Тёплая')], db_index=True, default='warm', help_text='Холодная/тёплая карточка (влияет на доступность отметок «холодный звонок»).', max_length=8, verbose_name='Состояние карточки'),
        ),
    ]
