# Generated by Django 6.0 on 2025-12-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_companynote_external_source_and_uid'),
    ]

    operations = [
    ]
