# Generated by Django 6.0 on 2025-01-XX XX:XX

from django.db import migrations
import re


def normalize_phone(phone: str) -> str:
    """Нормализует номер телефона в формат +7XXXXXXXXXX"""
    if not phone:
        return phone
    phone = str(phone).strip()
    if not phone:
        return phone
    
    # Убираем все нецифровые символы, кроме + в начале
    digits = ''.join(c for c in phone if c.isdigit() or (c == '+' and phone.startswith('+')))
    
    # Если начинается с +7, проверяем следующую цифру
    if digits.startswith('+7'):
        digits_only = digits[2:]  # Убираем +7
        # Если после +7 идет 8, убираем её (например +78XXXXXXXXX -> +7XXXXXXXXX)
        if digits_only.startswith('8') and len(digits_only) > 10:
            digits_only = digits_only[1:]
        # Если осталось 10 цифр, формируем +7XXXXXXXXXX
        if len(digits_only) == 10:
            return '+7' + digits_only
        else:
            return phone  # Не подходит под формат, оставляем как есть
    
    # Если начинается с 8 и 11 цифр, заменяем на +7
    if digits.startswith('8') and len(digits) == 11:
        return '+7' + digits[1:]
    
    # Если начинается с 7 и 11 цифр, добавляем +
    if digits.startswith('7') and len(digits) == 11:
        return '+' + digits
    
    # Если 10 цифр, добавляем +7
    if len(digits) == 10:
        return '+7' + digits
    
    # Иначе оставляем как есть
    return phone


def normalize_company_phones(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    ContactPhone = apps.get_model('companies', 'ContactPhone')
    
    # Нормализуем телефоны компаний
    for company in Company.objects.exclude(phone='').exclude(phone__isnull=True):
        normalized = normalize_phone(company.phone)
        if normalized != company.phone:
            company.phone = normalized
            company.save(update_fields=['phone'])
    
    # Нормализуем телефоны контактов
    for contact_phone in ContactPhone.objects.exclude(value='').exclude(value__isnull=True):
        normalized = normalize_phone(contact_phone.value)
        if normalized != contact_phone.value:
            contact_phone.value = normalized
            contact_phone.save(update_fields=['value'])


def reverse_normalize(apps, schema_editor):
    # Обратная миграция не требуется - просто оставляем номера как есть
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_fix_long_string_values'),
    ]

    operations = [
        migrations.RunPython(normalize_company_phones, reverse_normalize),
    ]
