# Generated by Django 6.0 on 2026-01-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_remove_company_lead_state_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companyemail',
            new_name='companies_c_value_a17e5d_idx',
            old_name='companies_c_value_idx',
        ),
        migrations.RenameIndex(
            model_name='companyemail',
            new_name='companies_c_company_90564b_idx',
            old_name='companies_c_company_order_idx',
        ),
        migrations.RenameIndex(
            model_name='companyphone',
            new_name='companies_c_value_b68823_idx',
            old_name='companies_c_phone_value_idx',
        ),
        migrations.RenameIndex(
            model_name='companyphone',
            new_name='companies_c_company_3cdaea_idx',
            old_name='companies_c_phone_company_order_idx',
        ),
    ]
