# Generated by Django 6.0 on 2026-01-21 10:52

from django.db import migrations




def _rename_indexes_pg(apps, schema_editor):
    """ALTER INDEX IF EXISTS работает только в PostgreSQL; для SQLite — пропускаем."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("ALTER INDEX IF EXISTS companies_c_value_idx RENAME TO companies_c_value_a17e5d_idx;")
    schema_editor.execute("ALTER INDEX IF EXISTS companies_c_company_order_idx RENAME TO companies_c_company_90564b_idx;")
    schema_editor.execute("ALTER INDEX IF EXISTS companies_c_phone_value_idx RENAME TO companies_c_value_b68823_idx;")
    schema_editor.execute("ALTER INDEX IF EXISTS companies_c_phone_company_order_idx RENAME TO companies_c_company_3cdaea_idx;")


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_remove_company_lead_state_request'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_rename_indexes_pg, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="companyemail",
                    old_name="companies_c_value_idx",
                    new_name="companies_c_value_a17e5d_idx",
                ),
                migrations.RenameIndex(
                    model_name="companyemail",
                    old_name="companies_c_company_order_idx",
                    new_name="companies_c_company_90564b_idx",
                ),
                migrations.RenameIndex(
                    model_name="companyphone",
                    old_name="companies_c_phone_value_idx",
                    new_name="companies_c_value_b68823_idx",
                ),
                migrations.RenameIndex(
                    model_name="companyphone",
                    old_name="companies_c_phone_company_order_idx",
                    new_name="companies_c_company_3cdaea_idx",
                ),
            ],
        ),
    ]
