# Generated by Django 6.0.1 on 2026-02-02 14:52

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_company_kpp_trgm_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysearchindex',
            name='normalized_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Нормализованные email (lower) из Company.email, CompanyEmail, ContactEmail'),
        ),
        migrations.AddField(
            model_name='companysearchindex',
            name='normalized_inns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='ИНН (только цифры, 10/12) из Company.inn (распарсенные списки)'),
        ),
        migrations.AddField(
            model_name='companysearchindex',
            name='normalized_phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Нормализованные телефоны (E.164 формат) из Company.phone, CompanyPhone, ContactPhone'),
        ),
        migrations.AddIndex(
            model_name='companysearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized_phones'], name='cmp_si_nphones_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='companysearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized_emails'], name='cmp_si_nemails_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='companysearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['normalized_inns'], name='cmp_si_ninns_gin_idx'),
        ),
    ]
