# Generated by Django 6.0.1 on 2026-02-03 21:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0043_add_exact_search_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysearchindex',
            name='normalized_inns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='ИНН (цифры 8–12) из Company.inn (parse_inns: 10/12 + fallback 8–12)'),
        ),
    ]
