# Generated by Django 6.0.1 on 2026-02-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0046_companydeal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companydeal',
            new_name='companies_c_company_81e1fd_idx',
            old_name='cmp_deal_co_created_idx',
        ),
    ]
