# Generated by Django 6.0.1 on 2026-02-13 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0047_rename_cmp_deal_co_created_idx_companies_c_company_81e1fd_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company_notes/%Y/%m/%d/', verbose_name='Файл')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла')),
                ('file_ext', models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='Расширение')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер (байт)')),
                ('content_type', models.CharField(blank=True, default='', max_length=120, verbose_name='MIME тип')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_attachments', to='companies.companynote', verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'Вложение заметки',
                'verbose_name_plural': 'Вложения заметок',
                'ordering': ['order', 'id'],
            },
        ),
    ]
