# Generated by Django 6.0 on 2026-03-12 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0048_note_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Создана'), ('assigned', 'Передана')], db_index=True, max_length=16, verbose_name='Тип события')),
                ('actor_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Кто выполнил (текст)')),
                ('from_user_name', models.CharField(blank=True, default='', max_length=255, verbose_name='От кого (текст)')),
                ('to_user_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Кому (текст)')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Когда произошло')),
                ('source', models.CharField(choices=[('local', 'CRM'), ('amocrm', 'amoCRM')], db_index=True, default='local', max_length=16, verbose_name='Источник')),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Внешний ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_history_events', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='companies.company', verbose_name='Компания')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'История компании',
                'verbose_name_plural': 'История компаний',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['company', '-occurred_at'], name='companies_c_company_1dcafc_idx')],
            },
        ),
    ]
