# Generated by Django 6.0 on 2026-04-02 12:57

from django.db import migrations, models


def classify_imported_notes(apps, schema_editor):
    """Classify existing imported notes by text content patterns, in batches."""
    CompanyNote = apps.get_model("companies", "CompanyNote")
    BATCH = 5000

    patterns = [
        ("Звонок · Исходящий", "call_out"),
        ("Звонок · Входящий", "call_in"),
        ("Письмо (amoMail) · Входящее", "email_in"),
        ("Письмо (amoMail) · Исходящее", "email_out"),
    ]

    for pattern, note_type in patterns:
        while True:
            ids = list(
                CompanyNote.objects.filter(
                    external_source="amo_api",
                    note_type="note",
                    text__contains=pattern,
                ).values_list("id", flat=True)[:BATCH]
            )
            if not ids:
                break
            CompanyNote.objects.filter(id__in=ids).update(note_type=note_type)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0049_companyhistoryevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='companynote',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AddField(
            model_name='companynote',
            name='note_type',
            field=models.CharField(choices=[('note', 'Заметка'), ('email_in', 'Входящее письмо'), ('email_out', 'Исходящее письмо'), ('call_in', 'Входящий звонок'), ('call_out', 'Исходящий звонок')], db_index=True, default='note', max_length=16, verbose_name='Тип записи'),
        ),
        migrations.RunPython(classify_imported_notes, migrations.RunPython.noop),
    ]
