# Generated by Django 6.0 on 2026-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0050_companynote_note_type_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynote',
            name='note_type',
            field=models.CharField(choices=[('note', 'Заметка'), ('email_in', 'Входящее письмо'), ('email_out', 'Исходящее письмо'), ('call_in', 'Входящий звонок'), ('call_out', 'Исходящий звонок'), ('sms', 'SMS')], db_index=True, default='note', max_length=16, verbose_name='Тип записи'),
        ),
    ]
