# Generated by Django 6.0 on 2026-04-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_duplicate_magiclink_index'),
        ('companies', '0051_companynote_sms_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='accounts.branch', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_company',
            field=models.ForeignKey(blank=True, help_text='Если эта карточка — подразделение клиента, выберите головную организацию.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_branches', to='companies.company', verbose_name='Головная организация'),
        ),
        migrations.AlterField(
            model_name='companydeletionrequest',
            name='requested_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.branch', verbose_name='Подразделение автора (снимок)'),
        ),
    ]
