# Generated by Django 6.0 on 2025-12-16 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='Текст письма (plain)')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='Текст письма (HTML)')),
                ('filter_meta', models.JSONField(blank=True, default=dict, verbose_name='Фильтр')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готово к отправке'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('stopped', 'Остановлено')], default='draft', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_id', models.UUIDField(blank=True, null=True, verbose_name='ID контакта')),
                ('company_id', models.UUIDField(blank=True, null=True, verbose_name='ID компании')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('unsubscribed', 'Отписался')], default='pending', max_length=16, verbose_name='Статус')),
                ('last_error', models.CharField(blank=True, default='', max_length=255, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='mailer.campaign', verbose_name='Кампания')),
            ],
        ),
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.yandex.ru', max_length=255, verbose_name='SMTP host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('use_starttls', models.BooleanField(default=True, verbose_name='STARTTLS')),
                ('smtp_username', models.CharField(default='', max_length=255, verbose_name='Логин SMTP')),
                ('smtp_password_enc', models.TextField(blank=True, default='', verbose_name='Пароль (зашифрован)')),
                ('from_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email отправителя')),
                ('from_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Имя отправителя')),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254, verbose_name='Reply-To')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Включено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='SendLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='smtp', max_length=50, verbose_name='Провайдер')),
                ('message_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Message-ID')),
                ('status', models.CharField(default='sent', max_length=32, verbose_name='Статус')),
                ('error', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='mailer.campaign', verbose_name='Кампания')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='mailer.campaignrecipient', verbose_name='Получатель')),
            ],
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='mailer_camp_campaig_142120_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['email'], name='mailer_camp_email_20c1f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'email')},
        ),
    ]
