# Generated by Django 6.0 on 2025-12-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
            ],
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='rate_per_day',
            field=models.PositiveIntegerField(default=500, verbose_name='Лимит писем в день'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='rate_per_minute',
            field=models.PositiveIntegerField(default=20, verbose_name='Лимит писем в минуту'),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='mailer.mailaccount', verbose_name='Аккаунт'),
        ),
    ]
