# Generated by Django 6.0 on 2026-01-21 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0016_unsubscribe_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaignqueue',
            new_name='mailer_camp_status_5db2fb_idx',
            old_name='mailer_camp_status_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcooldown',
            new_name='mailer_emai_created_817c96_idx',
            old_name='mailer_emai_created_7b9a3d_idx',
        ),
        migrations.RenameIndex(
            model_name='userdailylimitstatus',
            new_name='mailer_user_user_id_db59f8_idx',
            old_name='mailer_user_user_id_2a3b4c_idx',
        ),
        migrations.AlterField(
            model_name='emailcooldown',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_cooldowns', to=settings.AUTH_USER_MODEL),
        ),
    ]
