# Generated by Django 6.0 on 2026-01-21 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0016_unsubscribe_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS mailer_camp_status_priority_idx RENAME TO mailer_camp_status_5db2fb_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS mailer_camp_status_5db2fb_idx RENAME TO mailer_camp_status_priority_idx;",
                ),
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS mailer_emai_created_7b9a3d_idx RENAME TO mailer_emai_created_817c96_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS mailer_emai_created_817c96_idx RENAME TO mailer_emai_created_7b9a3d_idx;",
                ),
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS mailer_user_user_id_2a3b4c_idx RENAME TO mailer_user_user_id_db59f8_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS mailer_user_user_id_db59f8_idx RENAME TO mailer_user_user_id_2a3b4c_idx;",
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="campaignqueue",
                    old_name="mailer_camp_status_priority_idx",
                    new_name="mailer_camp_status_5db2fb_idx",
                ),
                migrations.RenameIndex(
                    model_name="emailcooldown",
                    old_name="mailer_emai_created_7b9a3d_idx",
                    new_name="mailer_emai_created_817c96_idx",
                ),
                migrations.RenameIndex(
                    model_name="userdailylimitstatus",
                    old_name="mailer_user_user_id_2a3b4c_idx",
                    new_name="mailer_user_user_id_db59f8_idx",
                ),
            ],
        ),
        migrations.AlterField(
            model_name='emailcooldown',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_cooldowns', to=settings.AUTH_USER_MODEL),
        ),
    ]
