# Generated by Django 6.0 on 2026-01-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0018_campaign_attachment_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignqueue',
            name='defer_reason',
            field=models.CharField(blank=True, default='', help_text='daily_limit, quota_exhausted, outside_hours, rate_per_hour', max_length=24, verbose_name='Причина отложения'),
        ),
        migrations.AddField(
            model_name='campaignqueue',
            name='deferred_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Продолжить не ранее'),
        ),
    ]
