# Generated by Django 6.0 on 2026-01-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0019_campaign_queue_deferred_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignqueue',
            name='consecutive_transient_errors',
            field=models.IntegerField(
                default=0,
                help_text='Используется для автоматической паузы при множественных ошибках SMTP',
                verbose_name='Последовательные transient ошибки'
            ),
        ),
    ]
