# Generated by Django 6.0 on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0020_campaignqueue_consecutive_transient_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignqueue',
            name='defer_reason',
            field=models.CharField(
                blank=True,
                default='',
                help_text='daily_limit, quota_exhausted, outside_hours, rate_per_hour, transient_error',
                max_length=24,
                verbose_name='Причина отложения'
            ),
        ),
    ]
