# Generated by Django 6.0 on 2026-03-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0021_alter_campaignqueue_defer_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_template',
            field=models.BooleanField(db_index=True, default=False, help_text='Шаблоны не отправляются и не показываются в списке кампаний — только как основа для новых.', verbose_name='Шаблон'),
        ),
    ]
