# Generated by Django 6.0 on 2026-03-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0022_campaign_is_template'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sendlog',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='mailer_send_provide_bb82e7_idx'),
        ),
        migrations.AddIndex(
            model_name='sendlog',
            index=models.Index(fields=['campaign', 'recipient', 'status'], name='mailer_send_campaig_aa2f9c_idx'),
        ),
    ]
