# Generated by Django 6.0 on 2026-03-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0023_sendlog_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrecipient',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ошибка'),
        ),
    ]
