# Generated by Django 6.0 on 2026-03-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0027_remove_globalmailaccount_smtp_bz_api_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaignqueue',
            new_name='mailer_camp_status_d674ce_idx',
            old_name='mailer_camp_status_deferred_idx',
        ),
        migrations.AlterField(
            model_name='sendlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Ошибка')], default='sent', max_length=32, verbose_name='Статус'),
        ),
    ]
