# Generated by Django 6.0 on 2026-03-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0028_sendlog_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='send_at',
            field=models.DateTimeField(blank=True, help_text='Если задано — рассылка не начнётся раньше этого времени.', null=True, verbose_name='Запланировано на'),
        ),
    ]
