# Generated by Django 6.0 on 2026-03-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0029_campaign_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignrecipient',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Ошибка'),
        ),
        migrations.AddConstraint(
            model_name='sendlog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'sent')), fields=('campaign', 'recipient'), name='mailer_sendlog_unique_sent_per_recipient'),
        ),
    ]
