# Generated by Django 6.0 on 2026-03-15 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0049_companyhistoryevent'),
        ('mailer', '0031_seed_global_mail_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.contact', verbose_name='Контакт'),
        ),
    ]
