# Generated by Django 6.0 on 2025-12-16 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('create', 'Создал'), ('update', 'Изменил'), ('delete', 'Удалил'), ('status', 'Сменил статус'), ('comment', 'Комментарий')], max_length=16, verbose_name='Действие')),
                ('entity_type', models.CharField(db_index=True, max_length=32, verbose_name='Сущность')),
                ('entity_id', models.CharField(db_index=True, max_length=64, verbose_name='ID сущности')),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID компании')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
