# Generated by Django 6.0 on 2026-01-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_errorlog'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS audit_error_created_idx RENAME TO audit_error_created_dc9bc2_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS audit_error_created_dc9bc2_idx RENAME TO audit_error_created_idx;",
                ),
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS audit_error_level_res_idx RENAME TO audit_error_level_bbfdc3_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS audit_error_level_bbfdc3_idx RENAME TO audit_error_level_res_idx;",
                ),
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS audit_error_path_res_idx RENAME TO audit_error_path_54ddb9_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS audit_error_path_54ddb9_idx RENAME TO audit_error_path_res_idx;",
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="errorlog",
                    old_name="audit_error_created_idx",
                    new_name="audit_error_created_dc9bc2_idx",
                ),
                migrations.RenameIndex(
                    model_name="errorlog",
                    old_name="audit_error_level_res_idx",
                    new_name="audit_error_level_bbfdc3_idx",
                ),
                migrations.RenameIndex(
                    model_name="errorlog",
                    old_name="audit_error_path_res_idx",
                    new_name="audit_error_path_54ddb9_idx",
                ),
            ],
        ),
    ]
