# Generated by Django 6.0 on 2026-01-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_errorlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='audit_error_created_dc9bc2_idx',
            old_name='audit_error_created_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='audit_error_level_bbfdc3_idx',
            old_name='audit_error_level_res_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='audit_error_path_54ddb9_idx',
            old_name='audit_error_path_res_idx',
        ),
    ]
