"""W2.6 cleanup: set unusable password on all non-admin users.

Companion to W2.6 JWT role filter (ab89c287). После закрытия /api/token/
password-пути для non-admin, их passwords — dormant code. Render unusable
через set_unusable_password() чтобы исключить dormant risk.

Staging baseline 2026-04-22: 17 non-admin с usable password
(10 MANAGER + 3 BRANCH_DIRECTOR + 2 SALES_HEAD + 2 GROUP_MANAGER + 0 TENDERIST).

Usage:
    python manage.py disable_non_admin_passwords --dry-run     # preview
    python manage.py disable_non_admin_passwords --confirm     # apply

Requires --dry-run OR --confirm. Default (no flag) refuses to apply changes.
"""

from __future__ import annotations

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.db.models import Q


class Command(BaseCommand):
    help = "W2.6: disable password auth для non-admin users (set_unusable_password)."

    def add_arguments(self, parser):
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Show what would change, без modifications.",
        )
        parser.add_argument(
            "--confirm",
            action="store_true",
            help="Actually apply changes (required to modify DB).",
        )

    def handle(self, *args, **options):
        User = get_user_model()

        # Non-admin users с usable password:
        #  - НЕ superuser
        #  - НЕ role=admin
        #  - password не пустой
        #  - password не начинается с "!" (Django convention для unusable)
        candidates = (
            User.objects.exclude(Q(is_superuser=True) | Q(role="admin"))
            .exclude(password="")
            .exclude(password__startswith="!")
            .order_by("role", "username")
        )

        count = candidates.count()
        self.stdout.write(f"Found {count} non-admin users с usable passwords:")

        # Breakdown by role
        by_role: dict[str, int] = {}
        for user in candidates:
            by_role[user.role] = by_role.get(user.role, 0) + 1

        for role, n in sorted(by_role.items()):
            self.stdout.write(f"  {role}: {n}")

        if count == 0:
            self.stdout.write(self.style.SUCCESS("No candidates — nothing to do."))
            return

        if options["dry_run"]:
            self.stdout.write(self.style.WARNING("\n=== DRY RUN — no changes applied ==="))
            self.stdout.write("Users that would be affected (first 20):")
            for user in candidates[:20]:
                self.stdout.write(f"  {user.username}  role={user.role}  email={user.email}")
            if count > 20:
                self.stdout.write(f"  ... and {count - 20} more")
            return

        if not options["confirm"]:
            self.stdout.write(
                self.style.ERROR(
                    "\nRefusing to apply: pass --confirm to actually change passwords, "
                    "or --dry-run to preview."
                )
            )
            return

        # Apply: set_unusable_password() per user. Django convention:
        # unusable password = "!" + random_salt (user.check_password('anything') returns False).
        changed = 0
        for user in candidates:
            user.set_unusable_password()
            user.save(update_fields=["password"])
            changed += 1

        self.stdout.write(
            self.style.SUCCESS(f"\n✅ Disabled password для {changed} non-admin users.")
        )
        self.stdout.write(
            "These users must now authenticate ONLY via magic link generated by admin\n"
            "(see /settings/admin/users/<id>/magic-link/generate/)."
        )
